### ISSUE TITLE
Samples return a 404 error on Github

### ISSUE THREAD

**Issue by nadjaklein** [MicrosoftDocs/bot-docs#904] opened 2019-02-27 12:59 UTC
Samples return a 404 error on Github:

Sample code
For two complete samples that show how to support Azure Search with bots using the Bot Framework SDK for Node.js, see the Real Estate Bot sample or Job Listing Bot sample in GitHub.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9cdb2f8-2862-a662-f01c-d8a3f26024c2
* Version Independent ID: 77444357-8674-41ae-6b81-c993190791f3
* Content: [Create data-driven experiences with Azure Search - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-search-azure?view=azure-bot-service-3.0)
* Content Source: [articles/nodejs/bot-builder-nodejs-search-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/nodejs/bot-builder-nodejs-search-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @matthewshim-ms
* Microsoft Alias: **v-shimma**

**Comment by JonathanFingold** [comment] 2019-02-27 18:24
Closing as a duplicate of #893

**Comment by nadjaklein** [comment] 2019-02-27 18:27
Hi Jonathan,

if this is a known issue – why don’t you update the links within the webpage? No user is going to look into the solved feedback comments!

Best regards,
Nadja

**Comment by JonathanFingold** [comment] 2019-02-27 18:29
We are actively working on issue #893, which is still open.

**Comment by DanDev33** [comment] 2019-02-27 20:44
This is a slightly different issue from #893 so I have reopened it and will correct these article links to point to the v3 sdk sample archive.

**Comment by DanDev33** [comment] 2019-02-27 20:58
Links have been updated and tested. You will see the corrected links when the next article update occurs. In the meantime you can look for the resources by changing "/master/" within these links to point to "/v3-sdk-samples/" instead. Here is one of the corrected links as an example: https://github.com/Microsoft/BotBuilder-Samples/tree/ v3-sdk-samples /Node/demo-Search/RealEstateBot

**Closed by DanDev33** 2019-02-27 20:58 UTC
Labels: v3 SDK
