### ISSUE TITLE
Sending Typing message gives 502 Bad Gateway Error

### ISSUE THREAD

**Issue by mkulgeorge** [MicrosoftDocs/bot-docs#1620] opened 2020-03-23 21:04 UTC
Hi Team,

I have been using the below code to send Typing message.
```
const reference = TurnContext.getConversationReference(turnContext.activity);
const activity = TurnContext.applyConversationReference({ type: 'typing' }, reference);
await turnContext.sendActivity(activity);
```

Until some time ago this was working perfectly, now it is giving a 502 Bad Gateway Error.

I saw the below code in this documentation page, even after implementing that I am getting the 502 Bad Gateway error.
```
        await turnContext.sendActivities([
			{ type: ActivityTypes.Typing }
		]);
```

Can you please help me resolve this issue?

Thanks,
George.

**Comment by iMicknl** [comment] 2020-03-23 21:24
Related to a recent outage which happened in Europe region; according to
https://github.com/microsoft/BotFramework-Services/issues/194#issuecomment-601249811.

**Comment by emgrol** [comment] 2020-03-25 21:38
Are you still experiencing issues @mkulgeorge?

**Comment by s-stefanov** [comment] 2020-03-26 11:04
We are still experiencing it @emgrol . This can be reproduced with generating an `Echo Bot` and just adding this `await context.sendActivity({ type: ActivityTypes.Typing });` to the `onMessage` handler.
Really a blocker to us on production.

**Comment by clearab** [comment] 2020-03-26 19:16
Due to the increased demand on Teams, they've temporarily limited a couple of things bot can do, including typing indicators. Please see [this blog post](https://developer.microsoft.com/en-us/microsoft-teams/blogs/outage-bots-posting-typing-indicators-will-receive-502s/). If you have additional questions or concerns, you can reach out to the Teams team in one of the methods outlined on [this page](https://aka.ms/teamsdevfeedback).

**Comment by emgrol** [comment] 2020-04-03 23:51
Closing this since this issue does not pertain specifically to any documentation.

**Closed by emgrol** 2020-04-03 23:51 UTC
Labels: WIP, source: customer
