### ISSUE TITLE
implementing dispatch with bot composer

### ISSUE THREAD

**Issue by Silu321** [MicrosoftDocs/bot-docs#1873] opened 2020-08-18 05:23 UTC
Hello, team 
I am  trying to implement dispatch with Bot composer But there is no documentation or guidance Can you please point out the correct documentation?
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c0c0448-d72d-3451-0b83-89b2fc93e0ab
* Version Independent ID: e3c31f64-02c7-046a-6a1f-a7408d68e5af
* Content: [Generators in adaptive dialogs - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-dialog-Generators?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/v4sdk/bot-builder-concept-adaptive-dialog-generators.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-concept-adaptive-dialog-generators.md)
* Service: **bot-service**
* GitHub Login: @emgrol
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment] 2020-08-25 05:30
What did you mean by "implement dispatch with Bot composer"? Can you specify more in detail?

**Comment by Silu321** [comment] 2020-08-25 06:55
"https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Dispatch" you just fallow this link but i need to implement these things through Microsoft Bot Frame Work Composer And i also implement #OAuth

**Comment by zxyanliu** [comment] 2020-08-25 16:00
For Composer OAuth, read this doc. 
https://docs.microsoft.com/en-us/composer/how-to-use-oauth

**Comment by Silu321** [comment] 2020-08-26 06:03
https://docs.microsoft.com/en-us/composer/how-to-use-oauth 
this doc only support GitHub authentication, but I need to implement outlook Authentication through Azure

**Comment by Silu321** [comment] 2020-08-26 10:26
Hello, team
I am trying to implement a #translator using #middleware with Bot composer But there is no documentation or guidance Can you please point out the correct documentation?

**Comment by zxyanliu** [comment] 2020-08-26 16:20
FYI. Composer will have multilingual support in the next release coming soon. 
By then, you can author bots in different languages. 
https://github.com/microsoft/BotFramework-Composer/releases

**Comment by Silu321** [comment] 2020-08-28 05:54
can you tell me about outlook OAuth and Middleware implementation

**Comment by zxyanliu** [comment] 2020-09-10 17:49
Closing as it is a duplicate of: https://github.com/MicrosoftDocs/bot-docs/issues/1874

**Closed by zxyanliu** 2020-09-10 17:49 UTC
Labels: platform: Composer
