### ISSUE TITLE
There shouldn't be separate C# and JavaScript sections in the "Republish your bot" section

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/bot-docs#1380] opened 2019-10-11 18:22 UTC
The process is the same for each (when using this AZ CLI method) and the C# section is erroneously missing the blurb about having to zip up your project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 466e4935-993f-ed61-0446-c6eff7310572
* Version Independent ID: 50fe83f8-c261-0bbe-5b8e-910ee27f17dc
* Content: [Azure Bot Service tutorial to have a bot answer questions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-add-qna?view=azure-bot-service-4.0&tabs=javascript#republish-your-bot)
* Content Source: [articles/v4sdk/bot-builder-tutorial-add-qna.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-tutorial-add-qna.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by zxyanliu** [comment] 2019-11-07 22:44
Hi @v-kydela 
Thanks for reporting this issue. I agree that there is no need to have two separate tabs (C# and JavaScript) while running the same command. 
I am going to walk through the process and update the content soon. 

Yan

**Comment by zxyanliu** [comment] 2019-11-13 23:51
addressing here: pr #[1820](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1820)

**Comment by zxyanliu** [comment] 2019-11-15 17:52
Closing because the issue is fixed in PR [1820](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1820) which just got merged. 
Thanks!

**Closed by zxyanliu** 2019-11-15 17:52 UTC
Labels: Deployment, QnA, WIP, source: other
