### ISSUE TITLE
TypeError: Cannot read property 'createProperty' of undefined

### ISSUE THREAD

**Issue by GourishVashisht** [MicrosoftDocs/bot-docs#816] opened 2019-02-03 17:43 UTC
Hi,
I did exaclty the same thing using node.js but it givs me this error, when i am creating property on user state.Why is it so please help? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c94a4c9-e988-3b42-a7db-3634d15e9c47
* Version Independent ID: 68765289-1d77-6e4a-c6fb-1abbc067fcbd
* Content: [Save user and conversation data - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-state?view=azure-bot-service-4.0&tabs=javascript)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-state.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-state.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment] 2019-02-06 18:54
Which steps are you referring to? Can you run the sample this topic refers to?

**Comment by GourishVashisht** [comment] 2019-02-07 19:10
constructor(conversationState, userState) {
    // Create the state property accessors for the conversation data and user profile.
    this.conversationData = conversationState.createProperty(CONVERSATION_DATA_PROPERTY);
    this.userProfile = userState.createProperty(USER_PROFILE_PROPERTY);

    // The state management objects for the conversation and user state.
    this.conversationState = conversationState;
    this.userState = userState;
}
While doing this step when i createProperty on coversation state it gives me an the error (cannot call createProperty on undefined), ans also if i did console.log of conversation state it was undefined.
Actually  i fixed this by a hit and trial method after changing the name of my bot whose constructor i was calling from index.js file passingthe user stae and the converstaion state.
Actully this error comes when my bot name is State and when i create object of this bot in index.js with both the memory storages then this error comes and both these storages are undefined when i print them in the constructor.
But on changing the name of the bot to something else (like MyStateBot) it worked perfectly fine.
I did not got the concept why this erro came when i names my bot State.

**Comment by JonathanFingold** [comment] 2019-02-19 23:49
I'm not sure, but there might be a name collision with `State`. Please close this if you are unblocked.

**Closed** 2019-02-21 23:43 UTC
Labels: v4 SDK

**Comment by Chatbot-Demo** [comment] 2019-06-25 11:12
> constructor(conversationState, userState) {
> // Create the state property accessors for the conversation data and user profile.
> this.conversationData = conversationState.createProperty(CONVERSATION_DATA_PROPERTY);
> this.userProfile = userState.createProperty(USER_PROFILE_PROPERTY);
> 
> ```
> // The state management objects for the conversation and user state.
> this.conversationState = conversationState;
> this.userState = userState;
> ```
> 
> }
> While doing this step when i createProperty on coversation state it gives me an the error (cannot call createProperty on undefined), ans also if i did console.log of conversation state it was undefined.
> Actually i fixed this by a hit and trial method after changing the name of my bot whose constructor i was calling from index.js file passingthe user stae and the converstaion state.
> Actully this error comes when my bot name is State and when i create object of this bot in index.js with both the memory storages then this error comes and both these storages are undefined when i print them in the constructor.
> But on changing the name of the bot to something else (like MyStateBot) it worked perfectly fine.
> I did not got the concept why this erro came when i names my bot State.

I think the issue is because you are not passing the constructor values in index.js

**Comment by sandeepindugupta** [comment] 2019-09-17 07:28
Hi,

I am getting same error as above when I am doing
constructor(conversationState, userState) {
// Create the state property accessors for the conversation data and user profile.
this.conversationData = conversationState.createProperty(CONVERSATION_DATA_PROPERTY);
this.userProfile = userState.createProperty(USER_PROFILE_PROPERTY);

// The state management objects for the conversation and user state.
this.conversationState = conversationState;
this.userState = userState;
}
and when I give createProperty on coversation state it gives me an the error "conversationState.createProperty is not a function"

could you please help in solving this issue.
Thanks in Advance..

**Comment by cswesh** [comment] 2022-12-03 10:16
you must be calling the constructor(conversationState, userState) in your bot.js file, but before that the bot object created by the toolkit should have the conversationState and userState be called and passed on to the object.
In the index.js file you should call this in declaration

```javascript
const { BotFrameworkAdapter, ConversationState, MemoryStorage, UserState } = require("botbuilder");
```
and pass this in the object

```javascript
// Create the bot that will handle incoming messages.
const memoryStorage = new MemoryStorage();
const conversationState = new ConversationState(memoryStorage);
const userState = new UserState(memoryStorage);

const bot = new TeamsBot(conversationState,userState);
```

**Comment by cswesh** [comment] 2022-12-03 10:20
> constructor(conversationState, userState) { // Create the state property accessors for the conversation data and user profile. this.conversationData = conversationState.createProperty(CONVERSATION_DATA_PROPERTY); this.userProfile = userState.createProperty(USER_PROFILE_PROPERTY);
> 
> ```
> // The state management objects for the conversation and user state.
> this.conversationState = conversationState;
> this.userState = userState;
> ```
> 
> } While doing this step when i createProperty on coversation state it gives me an the error (cannot call createProperty on undefined), ans also if i did console.log of conversation state it was undefined. Actually i fixed this by a hit and trial method after changing the name of my bot whose constructor i was calling from index.js file passingthe user stae and the converstaion state. Actully this error comes when my bot name is State and when i create object of this bot in index.js with both the memory storages then this error comes and both these storages are undefined when i print them in the constructor. But on changing the name of the bot to something else (like MyStateBot) it worked perfectly fine. I did not got the concept why this erro came when i names my bot State.

you must be calling the constructor(conversationState, userState) in your bot.js file, but before that the bot object created by the toolkit should have the conversationState and userState be called and passed on to the object.
In the index.js file you should call this in declaration

```javascript
const { BotFrameworkAdapter, ConversationState, MemoryStorage, UserState } = require("botbuilder");
```
and pass this in the object

```javascript
// Create the bot that will handle incoming messages.
const memoryStorage = new MemoryStorage();
const conversationState = new ConversationState(memoryStorage);
const userState = new UserState(memoryStorage);

const bot = new TeamsBot(conversationState,userState);
```
