### ISSUE TITLE
Example not 100% success

### ISSUE THREAD

**Issue by kuacci** [MicrosoftDocs/bot-docs#1827] opened 2020-07-14 06:06 UTC
I followed steps listed in this page, and I cannot make it work locally with emulator. It prompts 500 error.

Here is my environment information:
1. OS: Windows 10 1909
2. Python version: 3.7.7

I tried this example in a new virtual env.

After troubleshoot, I figured out that the latest package of cookiecutter not compatible with botbuilder-core. This issue has been mentioned in below repo, but you didn't update this document.
* [Dependency mismatch](https://github.com/microsoft/botbuilder-python/issues/1070)

The fix would be easy, we just uninstall cookiecutter then install a specific version 1.7.0 by pip. Then issue just gone.

please keep this document updated or list the correct package version. 

Thanks,
-Tony

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a20df2-727c-1afd-2b87-836ea1ea4f7a
* Version Independent ID: 157fc262-fb1f-f12d-0890-e90119feb444
* Content: [Create a bot using Bot Framework SDK for Python - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0)
* Content Source: [articles/python/bot-builder-python-quickstart.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/python/bot-builder-python-quickstart.md)
* Service: **bot-service**
* GitHub Login: @emgrol
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment] 2020-07-17 00:01
Thanks for pointing this out @kuacci. Closing this issue since it's a duplicate of [issue 1807](https://github.com/MicrosoftDocs/bot-docs/issues/1807).

**Closed by emgrol** 2020-07-17 00:01 UTC
Labels: issue type: fix: incorrect content, resolution: duplicate, source: customer
