### ISSUE TITLE
How do you create a subchild Dialog from another child Dialog?

### ISSUE THREAD

**Issue by DanteNahuel** [MicrosoftDocs/bot-docs#725] opened 2019-01-22 15:43 UTC
I'm using the Reuse Dialogs documentation to create separate .cs Dialogs to keep things tidy and organized. However I can't seem to call a new subchild dialog from the child dialog.cs
Is there a way to do this or the framework can't handle this? Because in V3 it was pretty easy.

**Comment by JonathanFingold** [comment] 2019-01-22 16:59
I haven't tried it myself, but I will. We should be able to nest them indefinitely.

**Comment by DanteNahuel** [comment] 2019-01-22 17:55
> I haven't tried it myself, but I will. We should be able to nest them indefinitely.

Thank you, Jonathan. I'm trying to understand why I'm not being able to, although I highly suspect this is due my lack of experience in V4.

**Comment by JonathanFingold** [comment] 2019-01-23 00:42
I think you have found a bug. I'll check to see if it is a known issue, and if not, open one.

**Comment by JonathanFingold** [comment] 2019-01-23 01:20
I spoke too soon, but I did find my error before submitting an issue. Here is partial sample code for a minimal bot with two, nested component dialogs. I don't know what tripped you up, but let me know if you need more.

I'm leaving out Startup and the usining and namespace statements...

```csharp
public class BotAccessors
{
    public const string DialogStateAccessorName = "DialogState";

    public BotAccessors(ConversationState conversationState)
    {
        ConversationState = conversationState;
    }

    public ConversationState ConversationState { get; }

    public IStatePropertyAccessor<DialogState> DialogStateAccessor { get; set; }
}

public class SubComponentDialogsBot : IBot
{
    private BotAccessors _botAccessors;

    private DialogSet _dialogs;

    public SubComponentDialogsBot(BotAccessors botAccessors)
    {
        _botAccessors = botAccessors ?? throw new ArgumentNullException(nameof(botAccessors));
        _dialogs = new DialogSet(_botAccessors.DialogStateAccessor)
            .Add(new Dialog1("main"));
    }

    public async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
    {
        if (turnContext.Activity.Type == ActivityTypes.Message)
        {
            var dc = await _dialogs.CreateContextAsync(turnContext, cancellationToken);
            var turnResult = await dc.ContinueDialogAsync(cancellationToken);
            switch (turnResult.Status)
            {
                case DialogTurnStatus.Complete:
                    await turnContext.SendActivityAsync("All done.");
                    break;
                case DialogTurnStatus.Empty:
                    await dc.BeginDialogAsync("main");
                    break;
            }
            await _botAccessors.ConversationState.SaveChangesAsync(turnContext);
        }
    }
}

public class Dialog1 : ComponentDialog
{
    public Dialog1(string id) : base(id)
    {
        InitialDialogId = "main";

        AddDialog(new TextPrompt("prompt"));
        AddDialog(new Dialog2("child"));

        AddDialog(new WaterfallDialog("main", new WaterfallStep[] {
            async (stepContext, cancellationToken) =>
            {
                return await stepContext.PromptAsync("prompt", new PromptOptions
                {
                    Prompt = MessageFactory.Text("Dialog 1: Enter text to continue."),
                    RetryPrompt = MessageFactory.Text("Dialog1: Try again?"),
                });
            },
            async (stepContext, cancellationToken) =>
            {
                await stepContext.Context.SendActivityAsync("Dialog 1: starting child.");
                return await stepContext.BeginDialogAsync("child");
            },
            async (stepContext, cancellationToken) =>
            {
                await stepContext.Context.SendActivityAsync($"Dialog 1: child returned '{stepContext.Result}'.");
                return await stepContext.EndDialogAsync(null, cancellationToken);
            },
        }));
    }
}

public class Dialog2 : ComponentDialog
{
    public Dialog2(string id) : base(id)
    {
        InitialDialogId = "main";

        AddDialog(new TextPrompt("prompt"));

        AddDialog(new WaterfallDialog("main", new WaterfallStep[] {
            Step1Async,
            Step2Async,
        }));
    }

    private static async Task<DialogTurnResult> Step1Async(
        WaterfallStepContext stepContext,
        CancellationToken cancellationToken = default(CancellationToken))
    {
        return await stepContext.PromptAsync("prompt", new PromptOptions
        {
            Prompt = MessageFactory.Text("Dialog 2: Enter text to continue."),
            RetryPrompt = MessageFactory.Text("Dialog2: Try again?"),
        });
    }

    private static async Task<DialogTurnResult> Step2Async(
        WaterfallStepContext stepContext,
        CancellationToken cancellationToken = default(CancellationToken))
    {
        var text = stepContext.Result as string;
        await stepContext.Context.SendActivityAsync($"Dialog 2: You typed '{text}'.");
        return await stepContext.EndDialogAsync(text, cancellationToken);
    }
}
```

**Comment by DanteNahuel** [comment] 2019-01-23 13:59
Jonathan, thank you for your help.
I've gotten so far as the example you posted, but what if I had a Dialog3 which I wanted to call from Dialog2?
Would the could be "identical" to the one over Dialog2?
Having also to use the AddDialog method to declare it over Dialog2 with with a different name, correct?


And this is beyond the scope of this opened question, but i'm struggling to comprehend what this does exactly:

` public Dialog1(string id) : base(id)
    {
        InitialDialogId = "main";`

Why the : base(id)
and the InitialDialogId = maindialogId?

Thanks in advance.

**Comment by JonathanFingold** [comment] 2019-01-23 17:59
Here's a partial answer (more later). The `id` in `base(id)` represents the ID of the component dialog from the outside, that is in the DialogSet to which the component dialog is getting added. The component dialog has an internal DialogSet. When the component is started, it begins the dialog in its internal set that has an ID of InitialDialogId.

Later today, I'll add more layers to the initial bot.

**Comment by JonathanFingold** [comment] 2019-01-24 17:22
Closing this as a duplicate of #734, as they seem to have converged. If this is not the case, feel free to reopen this or start a new issue.

**Closed by JonathanFingold** 2019-01-24 17:22 UTC
Labels: v4 SDK

**Comment by DanteNahuel** [comment] 2019-01-25 13:35
Thank you so much for it. I'll try to implement it and adapt it.
