### ISSUE TITLE
Unable to change Bot Icon and Display name

### ISSUE THREAD

**Issue by Vinay-Sopinti** [MicrosoftDocs/bot-docs#1460] opened 2019-11-28 11:55 UTC
I have been trying to change bot's display name and bot icon but changes are unable to reflect.
My custom bot icon and new display name are not showing up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b527247b-38f8-0bc0-6eda-af6382d8f1af
* Version Independent ID: e1c371cc-9183-1138-69e3-77a096a9f964
* Content: [Configure bot settings - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-settings?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-manage-settings.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-manage-settings.md)
* Service: **bot-service**
* GitHub Login: @v-royhar
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment] 2019-12-04 17:38
Closing as a duplicate of #1455. Please reopen with a clarification if this is not the case.

**Closed by JonathanFingold** 2019-12-04 17:38 UTC
Labels: duplicate, source: customer
