### ISSUE TITLE
Add information about how to create an App Registration

### ISSUE THREAD

**Issue by EricDahlvang** [MicrosoftDocs/bot-docs#1125] opened 2019-05-08 16:46 UTC
Some companies have a separate team who create app app registrations, and then provide the appid to other users who create the bot.  A Bot App Registration has specific requirements, including that it must be multi-tenant.  We have a good explanation for how to provide users with the necessary permissions to create a bot, but we have no documentation explaining how to create an app registration with the necessary requirements to use the appid for a bot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ac68200-6228-be59-af7b-275928efc159
* Version Independent ID: 2bea1252-bc31-a11f-5ceb-d5a652fd1476
* Content: [Troubleshooting bots - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-general-problems?view=azure-bot-service-4.0#why-do-i-get-an-authorization_requestdenied-exception-when-creating-a-bot)
* Content Source: [articles/bot-service-troubleshoot-general-problems.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-troubleshoot-general-problems.md)
* Service: **bot-service**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by mmiele** [comment] 2019-08-08 21:45
Eric, I am working on the issue https://github.com/MicrosoftDocs/bot-docs/issues/1136 related to the same problem you describe. Would you mind to take a look at the updated article staged at this location: [Register a bot with Azure Bot Service](https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0&branch=pr-en-us-1647)? Please, make sure that the description about appId and appSecret is correct. This might address the problem you raise. Let me know.

**Comment by mmiele** [comment] 2019-08-12 20:14
Closing because duplicate of:
[Need a new (or updated) doc that explains how to create the MIcrosoft App Id and Password in the Azure portal #1136](https://github.com/MicrosoftDocs/bot-docs/issues/1136).

**Closed by mmiele** 2019-08-12 20:14 UTC
Labels: source: other, type: feature request, v4 SDK
