### ISSUE TITLE
For MSBot the current link is giving 404. 

### ISSUE THREAD

**Issue by hamiltonjose** [MicrosoftDocs/bot-docs#261] opened 2018-09-05 16:17 UTC
The current url is: https://github.com/Microsoft/botbuilder-tools/tree/master/packages/MSBot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e258c266-773e-1e1f-7edf-cec09957ee8b
* Version Independent ID: 594cf0da-f103-7a89-afaa-38055e1f6921
* Content: [Create bots with Botbuilder Templates - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-create-templates?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-create-templates.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-create-templates.md)
* Product: **bot-framework**
* GitHub Login: @matthewshim-ms
* Microsoft Alias: **v-shimma**

**Comment by JonathanFingold** [comment] 2018-09-05 16:20
duplicate of #259

**Closed by JonathanFingold** 2018-09-05 16:20 UTC
