### ISSUE TITLE
How do I ensure my .bot file settings aren't user-readable after deployment?

### ISSUE THREAD

**Issue by jamestruitt** [MicrosoftDocs/bot-docs#796] opened 2019-01-30 17:42 UTC
While the deployment section doesn't outline putting the 'production' endpoint in the .bot file, I'm not comfortable doing so as the appid and password would be human-readable. There is no documentation on how to prevent people from reading these settings in the .bot file to separate roles in a DevOps environment (like we used to do with Application Settings on web apps).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your C# bot using Visual Studio - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment] 2019-02-06 18:49
If you encrypt the bot file using msbot tool before deploying back to azure, does that not work?

**Comment by JonathanFingold** [comment] 2019-02-27 20:31
Closing as a duplicate of #902.

**Closed by JonathanFingold** 2019-02-27 20:31 UTC
