### ISSUE TITLE
`convertFromUTC` returns different format than other date methods

### ISSUE THREAD

**Issue by chryw** [MicrosoftDocs/bot-docs#1927] opened 2020-10-06 01:25 UTC
Why does `convertFromUTC` return value look different than other UTC related methods? Am I supposed to format it myself? If so, what's the right format/locale? Thanks!

![image](https://user-images.githubusercontent.com/7075677/95147295-304dd380-0735-11eb-81bc-fc8246aa0fb1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5cc1453-1ec4-1ad7-2a9f-fa934224b79d
* Version Independent ID: 9645f547-d38a-4a22-c84b-ee98b7f24dfc
* Content: [Adaptive expressions prebuilt functions - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#convertFromUTC)
* Content Source: [articles/adaptive-expressions/adaptive-expressions-prebuilt-functions.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/adaptive-expressions/adaptive-expressions-prebuilt-functions.md)
* Service: **bot-service**
* GitHub Login: @Kamrani
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment] 2020-10-14 22:00
Hi @chryw, did you mean the `convertFromUTC` function? The return formats for `convertToUTC` and `utcNow` are the same (the default, which is YYYY-MM-DDTHH:mm:ss.fffZ) but I just tested `convertFromUTC` and that's returning the datetime value in a different format.

**Comment by chryw** [comment] 2020-10-15 16:59
@emgrol yes good catch. I made a typo. Just updated my question. Thanks! :-) 
I also just learned that "-07:00" party is called offset and I can easily remove it with string formatting. Just curious if this is by design though.

**Comment by emgrol** [comment] 2020-11-18 00:53
Sorry for the delay @chryw. I believe this by design since the function converts from UTC to a different format. Can you confirm this @boydc2014?

**Comment by cosmicshuai** [comment] 2020-11-18 05:51
Hi @chryw 
convertFromUtc means you convert a utc timestamp to a given timezone .
The "Z" in timestamp means it is a utc timestamp, which is the default for most time related adaptive-expression prebuilt functions.
However, the output of convertFromUtc does not follows the default format.
The output contains the timezone info. The offset "-07:00" indicates it is 7 hour later than the UTC timezone. 
So I'd like to suggest just remove the offset in the string.

**Comment by chryw** [comment] 2020-11-18 20:41
Thanks @cosmicshuai ! Yes I figured it out after some digging. Thanks for confirming. I did end up reformatting the string to remove the offset. 
Would it make sense to call out [the offset](https://en.wikipedia.org/wiki/UTC_offset) in the docs? BTW, the [current Wikipedia link](https://en.wikipedia.org/wiki/ISO**8601) is no longer valid. You may want to point to this https://en.wikipedia.org/wiki/ISO_8601 
![image](https://user-images.githubusercontent.com/7075677/99585590-6371bc80-299b-11eb-8bc2-8c02c7761e24.png)
Thanks!

**Comment by cosmicshuai** [comment] 2020-11-23 14:33
@chryw 
Thanks for the infomation. We will update the doc and the link of wikipedia. BTW, I think it will be better to remove offset in the result of convertFromUtc. I will discuss this with our team.

**Comment by cosmicshuai** [comment] 2020-11-25 09:53
@emgrol @chryw 
I have a PR for this issue.

**Comment by emgrol** [comment] 2020-12-16 21:25
Closing now that https://github.com/MicrosoftDocs/bot-docs-pr/pull/2484 has been merged.

**Closed by emgrol** 2020-12-16 21:25 UTC
Labels: component: adaptive expressions, source: other, status: dependency: code, status: writing
