### ISSUE TITLE
We could not connect to the bot before sending a message. 

### ISSUE THREAD

**Issue by mxxmusic** [MicrosoftDocs/bot-docs#1311] opened 2019-08-07 18:42 UTC
Run the uwp sample have the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa4cb4da-ca0e-fc7f-686c-f3510bf9af0b
* Version Independent ID: e20d2896-dcec-8e46-2f50-2227def34250
* Content: [Connect a bot to Direct Line Speech (Preview) - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-channel-connect-directlinespeech.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-directlinespeech.md)
* Service: **bot-service**
* GitHub Login: @trrwilson
* Microsoft Alias: **travisw**

**Comment by JonathanFingold** [comment] 2019-08-07 21:03
Closing as a duplicate of #1310.

**Closed by JonathanFingold** 2019-08-07 21:03 UTC
Labels: Direct Line, duplicate
