### ISSUE TITLE
Need user skype email id

### ISSUE THREAD

**Issue by seshadri322** [MicrosoftDocs/bot-docs#279] opened 2018-09-17 12:31 UTC
How to get skype user email id

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 486e6e6d-a7aa-2876-dfec-edc9d8a0d1ef
* Version Independent ID: aa6e5bfa-bbda-39ad-559e-62c92cbf5f86
* Content: [Connect a bot to Skype - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-skype?view=azure-bot-service-3.0)
* Content Source: [articles/bot-service-channel-connect-skype.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-connect-skype.md)
* Product: **bot-framework**
* GitHub Login: @v-ducvo
* Microsoft Alias: **RobStand**

**Comment by seshadri322** [comment] 2018-09-17 12:32
Is there any REST API to get the skype user email address ??

**Comment by Kaiqb** [comment] 2018-09-21 17:29
@seshadri322 - When you are adding the Skype channel, wheen are you being prompted for Skype user id/email?

**Comment by marknoble** [comment] 2018-10-01 18:28
Is this a duplicate of #244 ?

**Comment by Kaiqb** [comment] 2019-01-10 21:49
Closing due to lack of activity.

**Closed by Kaiqb** 2019-01-10 21:49 UTC
Labels: v3 SDK
