### ISSUE TITLE
[Bug Bash] Still sending users to old app registration portal which dies in May

### ISSUE THREAD

**Issue by jameslew** [MicrosoftDocs/bot-docs#1078] opened 2019-04-29 21:49 UTC
**Describe the bug**
In the docs when we explain to people where app registrations are created/managed.  Right now we're still sending them to the old dev center portal.

**To Reproduce**
1. Review this content:  https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0&branch=pr-en-us-1325&viewFallbackFrom=azure-bot-service-4.0#bot-channels-registration-password 

**Expected behavior**
We point them to the new portal

**Screenshots**

![image](https://user-images.githubusercontent.com/5997512/56929236-ed8ec300-6a8d-11e9-9fae-65cc5f75e44d.png)

**Comment by ivorb** [comment] 2019-04-30 17:23
dupe of #1062

**Closed by ivorb** 2019-04-30 17:23 UTC
Labels: P0, bugbash
