### ISSUE TITLE
Article should give guidance on encrypting the .bot file using the msbot tool

### ISSUE THREAD

**Issue by AndyCW** [MicrosoftDocs/bot-docs#770] opened 2019-01-29 00:13 UTC
The article explains how to update settings for a LUIS service in your .bot file. It needs to guide the developer to use the msbot tool to update the .bot file when it is encrypted. A developer new to bot development will be blocked unless this is explained

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b78c1c-bd0f-caec-32ad-47e6dfcc5b34
* Version Independent ID: 00957482-fbae-de4e-6c9c-49dae66c74af
* Content: [Add natural language understanding to your bot - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-luis?view=azure-bot-service-4.0&tabs=cs)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-luis.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-luis.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by DanDev33** [comment] 2019-01-29 17:38
Closed, Duplicate of same issue.

**Closed by DanDev33** 2019-01-29 17:38 UTC
Labels: v4 SDK
