### ISSUE TITLE
ERROR message "We could not connect to the bot before sending a message."

### ISSUE THREAD

**Issue by mxxmusic** [MicrosoftDocs/bot-docs#1309] opened 2019-08-07 17:34 UTC
my app code below:

`void CreateDialogServiceConnector()
{
	auto dialogServiceConfig = DialogServiceConfig::FromBotSecret("3-8O9RzmaKc.cwA.GHI.BrO4uSKLSdJcfl-GM29b-51YaJJZKxCpk_9gqlw1i8U", "f598b69a4ef141f3be247e4c93f574e8", "westus2");
	//dconfig->
	auto audioConfig = AudioConfig::FromDefaultMicrophoneInput();
	auto dialogServiceConnector = DialogServiceConnector::FromConfig(dialogServiceConfig, audioConfig);

	dialogServiceConnector->ConnectAsync();
	
	dialogServiceConnector->Recognizing.Connect([](const SpeechRecognitionEventArgs &e) {
		cout << "Recognizing:" << e.Result->Text << std::endl;
	});

	dialogServiceConnector->Recognized.Connect([](const SpeechRecognitionEventArgs &e) {
		cout << "Recognized---------------------" << std::endl;
	});
	dialogServiceConnector->ActivityReceived.Connect([](const ActivityReceivedEventArgs &e) {
		cout << "ActivityReceivedEventArgs---------------------" << std::endl;
	});

	dialogServiceConnector->Canceled.Connect([](const SpeechRecognitionCanceledEventArgs &e) {
		cout << "KWS CANCELED: Reason=" << (int)e.Reason << std::endl;
		if (e.Reason == CancellationReason::Error)
		{
			cout << "CANCELED: ErrorCode=" << (int)e.ErrorCode << "\n"
				<< "CANCELED: ErrorDetails=" << e.ErrorDetails << "\n"
				<< "CANCELED: Did you update the subscription info?" << std::endl;
		}
	});

	dialogServiceConnector->SessionStarted.Connect([](const SessionEventArgs &e) {
		cout << "SESSIONSTARTED: SessionId=" << e.SessionId << std::endl;
	});

	dialogServiceConnector->SessionStopped.Connect([/* &recognitionEnd */](const SessionEventArgs &e) {
		cout << "SESSIONSTOPPED: SessionId=" << e.SessionId << std::endl;
		//recognitionEnd.set_value(); // Notify to stop recognition.
	});

	dialogServiceConnector->ListenOnceAsync().get();

	cout << "ListenOnceAsync" << std::endl;
}`

my bot channel setting by this url:
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-directlinespeech?view=azure-bot-service-4.0

my app get the error massage:
SESSIONSTARTED: SessionId=b3430096-c433-465b-a8d2-e73d5ad2fd7e
Recognizing:hello hello
Recognizing:hello hello what's
Recognizing:hello hello what's your
Recognizing:hello hello what's your name
Recognized---------------------
KWS CANCELED: Reason=1
CANCELED: ErrorCode=5
CANCELED: ErrorDetails=Connection was closed by the remote host. Error code: 1011. Error details: We could not connect to the bot before sending a message.
CANCELED: Did you update the subscription info?

and in by bot channel get have the issues like :
We could not connect to the bot before sending a message.

**Comment by JonathanFingold** [comment] 2019-08-07 21:04
Closing as a duplicate of #1310.

**Closed by JonathanFingold** 2019-08-07 21:04 UTC
Labels: Direct Line, duplicate
