### ISSUE TITLE
Lack of story for deploying Node bot the way you would deploy any other Node Azure Web App

### ISSUE THREAD

**Issue by ryanvolum** [MicrosoftDocs/bot-docs#641] opened 2018-12-14 23:37 UTC
On the C# front, developers can use VS tooling to deploy a bot the way you would deploy any Azure web app. 

On the Node front, the only documented way to deploy a bot is using the CLI tools, which present substantial confusion and friction. Given that a bot is just a web app developers are lacking guidance on deploying their Node bots the way they would deploy any other Node Azure Web App.

**Comment by Kaiqb** [comment] 2018-12-18 00:12
The issue is that there is bit more to a bot than jsut web app piece. The deployment needs a registration bot to connect the web app to the bot. The tooling definitely needs to be fixed and content will evolve as the tooling does. I'm going to close this issue as this is a deployment tooling issue and not a docs issue.

**Closed by Kaiqb** 2018-12-18 00:12 UTC
Labels: v4 SDK
