### ISSUE TITLE
Get Conversations does not work

### ISSUE THREAD

**Issue by dgancho** [MicrosoftDocs/bot-docs#1264] opened 2019-07-17 03:31 UTC
GET to "/v3/conversations?continuationToken={continuationToken}" (with or without a continuationToken)
Returns (405) Method Not Allowed {"message":"The requested resource does not support http method 'GET'."}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36ddb50-9e44-96e3-2df3-174166efa75d
* Version Independent ID: 68ac4b64-6616-2216-3519-e0b33d3a53e4
* Content: [API reference - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#get-conversations)
* Content Source: [articles/rest-api/bot-framework-rest-connector-api-reference.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-api-reference.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by JonathanFingold** [comment] 2019-07-30 16:59
This Bot Connector service /v3/conversations endpoint supports the GET method, so I'm not sure what is causing the 405 HTTP response. I've labeled this as a support issue, and someone from that team should respond.

In the mean time, can you provide a little more information about your environment?

**Comment by CoHealer** [comment] 2019-08-01 17:32
Assigning @jwiley84 to investigate

**Comment by CoHealer** [comment] 2019-08-01 19:45
Load balancing, assigning to @mdrichardson to investigate.

**Comment by mdrichardson** [comment] 2019-08-01 21:20
@dgancho 	What base URL are you using (ie `https://smba.trafficmanager.net/apis/`)?

**Comment by mdrichardson** [comment] 2019-08-02 21:51
I've confirmed I can repro and this doesn't appear to be desired. @ToddN 	is reaching out to some folks to dig into this a little more.

**Comment by mdrichardson** [comment] 2019-08-02 22:52
[Possibly related](https://github.com/microsoft/BotFramework-Services/issues/88)

**Comment by mdrichardson** [comment] 2019-08-05 18:47
@dgancho 	Per the issue I linked in my previous comment, GET `/conversations` works as intended. I am unsure why you are getting a 405; using the code in the linked issue works fine for me. Can you include your code?

**Comment by CoHealer** [comment] 2019-08-08 18:28
@dgancho, do you still require assistance? We're going to close it without a response.

**Closed** 2019-08-12 15:12 UTC
Labels: Support, source: customer
