### ISSUE TITLE
CosmoDB not working (using Azure with free subscription)

### ISSUE THREAD

**Issue by Wendy-YongAiJing** [MicrosoftDocs/bot-docs#882] opened 2019-02-21 03:42 UTC
Sorry for re-posting this issue, as I'm urged for the solution.

I'm building bot in C#. After I able to use memory storage, I update my code to use CosmoDB. I followed the instruction by changing this code
private static readonly MemoryStorage _myStorage = new MemoryStorage();
to
private static readonly CosmosDbStorage _myStorage = new CosmosDbStorage(new CosmosDbStorageOptions
{
AuthKey = CosmosDBKey,
CollectionId = CosmosDBCollectionName,
CosmosDBEndpoint = new Uri(CosmosServiceEndpoint),
DatabaseId = CosmosDBDatabaseName,
});
There is no error showing in my coding but when I start my bot, it shows me message "Sorry, it looks like something went wrong."

When I create CosmoDB database account in Azure, I did chose SQL; same resource group and subscription; leave Geo-redundancy as default (enable) ; also leave Multi-region Write as default (disable)

Then I copy endpoint URL and PRIMARY KEY found in Key tab to my code there as :
private const string CosmosServiceEndpoint = "https://webprojectcosmodb.documents.azure.com:443/";
private const string CosmosDBKey = "1chn..............";
private const string CosmosDBDatabaseName = "bot-cosmos-sql-db";
private const string CosmosDBCollectionName = "bot-storage";

Much appreciation anyone could help me!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8f39f5-1a91-6fdb-3cc0-124b282e9806
* Version Independent ID: 701f9b3c-a893-dee1-d012-760e6f870ec4
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?view=azure-bot-service-4.0&tabs=csharp#memory-storage)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by ivorb** [comment] 2019-02-21 16:43
Duplicate of https://github.com/MicrosoftDocs/bot-docs/issues/848 which is being worked on

**Closed by ivorb** 2019-02-21 16:43 UTC
