### ISSUE TITLE
onTurnError: TypeError: Only absolute URLs are supported

### ISSUE THREAD

**Issue by ebbimola** [MicrosoftDocs/bot-docs#1339] opened 2019-08-30 15:23 UTC
onTurnError 
 
It was initially a scaffold echo bot.
QnA code to call QnA maker service were added, but now after the bot echos back, I get the following: "Oops. Something went wrong".
The emulator returns:  [onTurnError]: TypeError: Only absolute URLs are supported
What could cause this error?

**Comment by JonathanFingold** [comment] 2019-08-30 15:51
@ebbimola Which article were you following when you received this error message?

**Comment by ebbimola** [comment] 2019-08-30 16:01
That will be "Use QnA Maker in your bot to answer questions"

**Comment by ebbimola** [comment] 2019-08-30 16:50
`onst dotenv = require('dotenv');
const path = require('path');
const restify = require('restify');

const { BotFrameworkAdapter } = require('botbuilder');

const { MyBot } = require('./bot');

const ENV_FILE = path.join(__dirname, '.env');
dotenv.config({ path: ENV_FILE });

// Create HTTP server
const server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, () => {
    console.log(`\n${ server.name } listening to ${ server.url }`);
    console.log(`\nGet Bot Framework Emulator: https://aka.ms/botframework-emulator`);
    console.log(`\nTo test your bot, see: https://aka.ms/debug-with-emulator`);
});

// Create adapter.
const adapter = new BotFrameworkAdapter({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
});

// Map knowledge base endpoint values from .env file into the required format for `QnAMaker`.
const configuration = {
    knowledgeBaseId: process.env.QnAKnowledgebaseId,
    endpointKey: process.env.QnAAuthKey,
    host: process.env.QnAEndpointHostName
 };

// Catch-all for errors.
adapter.onTurnError = async (context, error) => {
    // This check writes out errors to console log .vs. app insights.
    console.error(`\n [onTurnError]: ${ error }`);
    // Send a message to the user
    await context.sendActivity(`Oops. Something went wrong! this Damn thing....`);
};

// Create the main dialog.
const myBot = new MyBot(configuration, {});

// Listen for incoming requests.
server.post('/api/messages', (req, res) => {
    adapter.processActivity(req, res, async (context) => {
        // Route to main dialog.
        await myBot.run(context);
    });
});
`

**Comment by JonathanFingold** [comment] 2019-08-30 19:02
Your host name should look something like this:
![image](https://user-images.githubusercontent.com/35047199/64045343-dd5f2100-cb1d-11e9-82fe-d9fa6d8aa69c.png)
Use the complete name, starting with `https://` and ending with `/qnamaker`.

**Comment by ebbimola** [comment] 2019-08-31 20:41
@jonathanFingold my .env file has the full url as shown below

![image](https://user-images.githubusercontent.com/8404885/64068962-f78d2200-cc37-11e9-8d55-7af3f2eef7c6.png)

the error persist...

**Comment by dmvtech** [comment] 2019-09-03 20:29
I'm seeing if I reproduce with your code from a echo bot. In the meantime, can you clone and try with the [QnA sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/11.qnamaker), I just confirmed that this one worked for me.

**Comment by dmvtech** [comment] 2019-09-03 21:05
@ebbimola Can you share your bot code too? What does the Debug Console show for errors?

**Comment by ebbimola** [comment] 2019-09-04 10:21
`onst dotenv = require('dotenv');
const path = require('path');
const restify = require('restify');

// Import required bot services.
// See https://aka.ms/bot-services to learn more about the different parts of a bot.
const { BotFrameworkAdapter } = require('botbuilder');

// This bot's main dialog.
const { MyBot } = require('./bot');

// Import required bot configuration.
const ENV_FILE = path.join(__dirname, '.env');
dotenv.config({ path: ENV_FILE });

// Create HTTP server
const server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, () => {
    console.log(`\n${ server.name } listening to ${ server.url }`);
    console.log(`\nGet Bot Framework Emulator: https://aka.ms/botframework-emulator`);
    console.log(`\nTo test your bot, see: https://aka.ms/debug-with-emulator`);
});

// Create adapter.
// See https://aka.ms/about-bot-adapter to learn more about how bots work.
const adapter = new BotFrameworkAdapter({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
});

// Map knowledge base endpoint values from .env file into the required format for `QnAMaker`.
const configuration = {
    knowledgeBaseId: process.env.QnAKnowledgebaseId,
    endpointKey: process.env.QnAAuthKey,
    host: process.env.QnAEndpointHostName
 };


// Catch-all for errors.
adapter.onTurnError = async (context, error) => {
    // This check writes out errors to console log .vs. app insights.
    console.error(`\n [onTurnError]: ${ error }`);
    // Send a message to the user
    await context.sendActivity(`Oops. Something went wrong! this Damn thing....`);
};

// Create the main dialog.
const myBot = new MyBot(configuration, {});

// Listen for incoming requests.
server.post('/api/messages', (req, res) => {
    adapter.processActivity(req, res, async (context) => {
        // Route to main dialog.
        await myBot.run(context);
    });
});
`

**Comment by ebbimola** [comment] 2019-09-04 10:24
I get the below error in the console...
![image](https://user-images.githubusercontent.com/8404885/64247322-81720f00-cf06-11e9-88a0-2b7c87869a3d.png)

**Comment by dmvtech** [comment] 2019-09-04 18:58
@ebbimola That code is from your index.js, yes? You should also have code in a bot (for example bot.js or bots\echobot.js). If it's easier, you can put your bot in a repo so I can see the whole thing.

**Comment by dmvtech** [comment] 2019-09-04 19:06
Also, is this a typo?

`onst dotenv = require('dotenv');

Should be:

**c**onst dotenv = require('dotenv');

**Comment by ebbimola** [comment] 2019-09-04 19:32
`const { ActivityHandler } = require('botbuilder');


class MyBot extends ActivityHandler {
    constructor(configuration, qnaOptions) {
       super();
       if (!configuration) throw new Error('[QnaMakerBot]: Missing parameter. configuration is required');
       // now create a qnaMaker connector.
       this.qnaMaker = new QnAMaker(configuration, qnaOptions);
       this.onMessage(async (context, next) => {
            await context.sendActivity(`You said '${ context.activity.text }'`);
            // send user input to QnA Maker.
            const qnaResults = await this.qnaMaker.getAnswers(context);
        
            // If an answer was received from QnA Maker, send the answer back to the user.
            if (qnaResults[0]) {
                await context.sendActivity(`QnAMaker returned response: ' ${ qnaResults[0].answer}`);
            }
            else {
                // If no answers were returned from QnA Maker, reply with help.
                await context.sendActivity('No QnA Maker response was returned.'
                    + 'This example uses a QnA Maker Knowledge Base that focuses on smart light bulbs. '
                    + `Ask the bot questions like "Why won't it turn on?" or "I need help."`);
            }
            await next();
         });
    
            this.onMembersAdded(async (context, next) => {
                const membersAdded = context.activity.membersAdded;
                for (let cnt = 0; cnt < membersAdded.length; ++cnt) {
                    if (membersAdded[cnt].id !== context.activity.recipient.id) {
                        await context.sendActivity('Hello and welcome!');
                    }
                }
                // By calling next() you ensure that the next BotHandler is run.
                await next();
            });
    }
}
module.exports.MyBot = MyBot;
const { QnAMaker } = require('botbuilder-ai');`

**Comment by ebbimola** [comment] 2019-09-04 19:36
const { ActivityHandler } = require('botbuilder');

class MyBot extends ActivityHandler {
    constructor(configuration, qnaOptions) {
       super();
       if (!configuration) throw new Error('[QnaMakerBot]: Missing parameter. configuration is required');
       // now create a qnaMaker connector.
       this.qnaMaker = new QnAMaker(configuration, qnaOptions);
       this.onMessage(async (context, next) => {
            await context.sendActivity(`You said '${ context.activity.text }'`);
            // send user input to QnA Maker.
            const qnaResults = await this.qnaMaker.getAnswers(context);
        
            // If an answer was received from QnA Maker, send the answer back to the user.
            if (qnaResults[0]) {
                await context.sendActivity(`QnAMaker returned response: ' ${ qnaResults[0].answer}`);
            }
            else {
                // If no answers were returned from QnA Maker, reply with help.
                await context.sendActivity('No QnA Maker response was returned.'
                    + 'This example uses a QnA Maker Knowledge Base that focuses on smart light bulbs. '
                    + `Ask the bot questions like "Why won't it turn on?" or "I need help."`);
            }
            await next();
         });
    
            this.onMembersAdded(async (context, next) => {
                const membersAdded = context.activity.membersAdded;
                for (let cnt = 0; cnt < membersAdded.length; ++cnt) {
                    if (membersAdded[cnt].id !== context.activity.recipient.id) {
                        await context.sendActivity('Hello and welcome!');
                    }
                }
                // By calling next() you ensure that the next BotHandler is run.
                await next();
            });
    }
}
module.exports.MyBot = MyBot;
const { QnAMaker } = require('botbuilder-ai');

**Comment by ebbimola** [comment] 2019-09-04 19:37
onst { ActivityHandler } = require('botbuilder');



class MyBot extends ActivityHandler {
    constructor(configuration, qnaOptions) {
       super();
       if (!configuration) throw new Error('[QnaMakerBot]: Missing parameter. configuration is      required');
       // now create a qnaMaker connector.
       this.qnaMaker = new QnAMaker(configuration, qnaOptions);
       this.onMessage(async (context, next) => {
            await context.sendActivity(`You said '${ context.activity.text }'`);
            // send user input to QnA Maker.
            const qnaResults = await this.qnaMaker.getAnswers(context);
        
            // If an answer was received from QnA Maker, send the answer back to the user.
            if (qnaResults[0]) {
                await context.sendActivity(`QnAMaker returned response: ' ${ qnaResults[0].answer}`);
            }
            else {
                // If no answers were returned from QnA Maker, reply with help.
                await context.sendActivity('No QnA Maker response was returned.'
                    + 'This example uses a QnA Maker Knowledge Base that focuses on smart light bulbs. '
                    + `Ask the bot questions like "Why won't it turn on?" or "I need help."`);
            }
            await next();
         });
    
            this.onMembersAdded(async (context, next) => {
                const membersAdded = context.activity.membersAdded;
                for (let cnt = 0; cnt < membersAdded.length; ++cnt) {
                    if (membersAdded[cnt].id !== context.activity.recipient.id) {
                        await context.sendActivity('Hello and welcome!');
                    }
                }
                // By calling next() you ensure that the next BotHandler is run.
                await next();
            });
    }
}
module.exports.MyBot = MyBot;
const { QnAMaker } = require('botbuilder-ai');

**Comment by ebbimola** [comment] 2019-09-04 19:40
@dmvtech I am sorry it was an oversight, and yes theres bot.js and also typo most have been when I was copying the code.

> const { ActivityHandler } = require('botbuilder');



class MyBot extends ActivityHandler {
    constructor(configuration, qnaOptions) {
       super();
       if (!configuration) throw new Error('[QnaMakerBot]: Missing parameter. configuration is required');
       // now create a qnaMaker connector.
       this.qnaMaker = new QnAMaker(configuration, qnaOptions);
       this.onMessage(async (context, next) => {
            await context.sendActivity(`You said '${ context.activity.text }'`);
            // send user input to QnA Maker.
            const qnaResults = await this.qnaMaker.getAnswers(context);
        
            // If an answer was received from QnA Maker, send the answer back to the user.
            if (qnaResults[0]) {
                await context.sendActivity(`QnAMaker returned response: ' ${ qnaResults[0].answer}`);
            }
            else {
                // If no answers were returned from QnA Maker, reply with help.
                await context.sendActivity('No QnA Maker response was returned.'
                    + 'This example uses a QnA Maker Knowledge Base that focuses on smart light bulbs. '
                    + `Ask the bot questions like "Why won't it turn on?" or "I need help."`);
            }
            await next();
         });
    
            this.onMembersAdded(async (context, next) => {
                const membersAdded = context.activity.membersAdded;
                for (let cnt = 0; cnt < membersAdded.length; ++cnt) {
                    if (membersAdded[cnt].id !== context.activity.recipient.id) {
                        await context.sendActivity('Hello and welcome!');
                    }
                }
                // By calling next() you ensure that the next BotHandler is run.
                await next();
            });
    }
}
module.exports.MyBot = MyBot;
const { QnAMaker } = require('botbuilder-ai');

**Comment by ebbimola** [comment] 2019-09-04 19:43
@dmvtech I am sorry it was an oversight, and yes theres bot.js and also typo most have been when I was copying the code.

**Comment by dmvtech** [comment] 2019-09-05 15:37
Can you share the bot.js code?

**Comment by ebbimola** [comment] 2019-09-06 10:11
`const { ActivityHandler } = require('botbuilder');
`

`class MyBot extends ActivityHandler {
    constructor(configuration, qnaOptions) {
       super();
       if (!configuration) throw new Error('[QnaMakerBot]: Missing parameter. configuration is required');
       // now create a qnaMaker connector.
       this.qnaMaker = new QnAMaker(configuration, qnaOptions);
       this.onMessage(async (context, next) => {
            await context.sendActivity(`You said '${ context.activity.text }'`);
            // send user input to QnA Maker.
            const qnaResults = await this.qnaMaker.getAnswers(context);
        
            // If an answer was received from QnA Maker, send the answer back to the user.
            if (qnaResults[0]) {
                await context.sendActivity(`QnAMaker returned response: ' ${ qnaResults[0].answer}`);
            }
`
` else {
                // If no answers were returned from QnA Maker, reply with help.
                await context.sendActivity('No QnA Maker response was returned.'
                    + 'This example uses a QnA Maker Knowledge Base that focuses on smart light bulbs. '
                    + `Ask the bot questions like "Why won't it turn on?" or "I need help."`);
            }
            await next();
         });
`
`this.onMembersAdded(async (context, next) => {
                const membersAdded = context.activity.membersAdded;
                for (let cnt = 0; cnt < membersAdded.length; ++cnt) {
                    if (membersAdded[cnt].id !== context.activity.recipient.id) {
                        await context.sendActivity('Hello and welcome!');
                    }
                }
                // By calling next() you ensure that the next BotHandler is run.
                await next();
            });
    }
}
`
`module.exports.MyBot = MyBot;
const { QnAMaker } = require('botbuilder-ai');
`

**Comment by dmvtech** [comment] 2019-09-10 18:42
I'm not able to reproduce the error using your code. 

Have you tried creating another QnA KB and testing against that?

May I email you my keys/endpoint and have you test with that?

**Comment by dmvtech** [comment] 2019-09-10 18:46
I sent you an email.

**Comment by ebbimola** [comment] 2019-09-11 15:17
@dmvtech thanks, yes I have created another QnA and it worked with my keys and endpoint.

**Comment by dmvtech** [comment] 2019-09-11 16:36
Thanks @ebbimola. That shows that there is something wrong with that KB. You could test by using the POSTMAN or CURL commands that it gives you after publishing.

To clarify for me; is that (another QnA KB) a solution for you or just a test? (i.e. are you going to be using the other QnA KB as your production one).

**Comment by dmvtech** [comment] 2019-09-13 19:48
I'm going to close this as you have a work around. If you still have issues, please let me know.

**Closed by dmvtech** 2019-09-13 19:48 UTC
Labels: Support, help wanted, source: customer

**Comment by MaxMueller0815** [comment] 2019-10-25 22:25
I have the exact same error.
Only in the local testing with the emulator the code works.
When I pushed it in git hub and it was deployed in azure it worked in web chat today in the morning.
now I have the error above.

**Comment by dmvtech** [comment] 2019-10-28 17:23
@MaxMueller0815 I just wanted to check. You are still having this issue as of October 28th?

**Comment by MaxMueller0815** [comment] 2019-10-28 17:29
Thanks for asking
I already tried different other samples. I cannot remember which one was causing this error.
If i find out i will update my post!

**Comment by nandaguruswamy** [comment] 2019-12-31 09:53
I had the same error too and found the reason. Its the .env file, the last line of the hostname is not commented out properly. Remove the line "// This is a URL ending in /qnamaker". And it should work. Hope this helps.

**Comment by Catalyst546** [comment] 2022-06-21 04:45
Please, I have the error above in my code when I run through the bot emulator; it works when I test the QnAMaker with Postman though. Any pointers?
`[onTurnError] unhandled error: TypeError: Only absolute URLs are supported`

`My bot.js
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

const { ActivityHandler, MessageFactory } = require('botbuilder');

const { QnAMaker } = require('botbuilder-ai');
const DentistScheduler = require('./dentistscheduler');
const IntentRecognizer = require('./intentrecognizer');

class DentaBot extends ActivityHandler {
    constructor(configuration, qnaOptions) {
    // call the parent constructor
        super();
        if (!configuration) {
            throw new Error(
                '[QnaMakerBot]: Missing parameter. configuration is required'
            );
        }

        // create a QnAMaker connector
        this.qnAMaker = new QnAMaker(configuration, qnaOptions);

        // create a DentistScheduler connector

        this.dentistScheduler = new DentistScheduler(configuration);

        // create a IntentRecognizer connector
        this.intentRecognizer = new IntentRecognizer(configuration);

        this.onMessage(async (context, next) => {
            
            if (!this.qnAMaker) {
                const unconfiguredQnaMessage =
          'NOTE: \r\n' +
          'QnA Maker is not configured. To enable all capabilities, add `QnAKnowledgebaseId`, `QnAEndpointKey` and `QnAEndpointHostName` to the .env file. \r\n' +
          'You may visit www.qnamaker.ai to create a QnA Maker knowledge base.';

                await context.sendActivity(unconfiguredQnaMessage);
            } else {
                console.log('Calling QnA Maker');

                const qnaResults = await this.qnAMaker.getAnswers(context);
                console.log('qnaResults : ', qnaResults);

                // If an answer was received from QnA Maker, send the answer back to the user.
                if (qnaResults[0]) {
                    await context.sendActivity(qnaResults[0].answer);
                    console.log('qnaResults[0] answer: ', qnaResults[0].answer);
                    // If no answers were returned from QnA Maker, reply with help.
                } else {
                    await context.sendActivity('No QnA Maker answers were found.');
                    console.log('Else : No QnA Maker answers were found.');
                }
            }

            /* const replyText = `Echo: ${ context.activity.text }`;
            await context.sendActivity(MessageFactory.text(replyText, replyText));
 */
            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });

        this.onMembersAdded(async (context, next) => {
            const membersAdded = context.activity.membersAdded;
            // write a custom greeting
            const welcomeText = `Welcome to Dental Virtual Assistant. 
        Please our assistance is currently limited to checking availability and scheduling an appointment. 
        Kindly take note of that.`;
            for (let cnt = 0; cnt < membersAdded.length; ++cnt) {
                if (membersAdded[cnt].id !== context.activity.recipient.id) {
                    await context.sendActivity(
                        MessageFactory.text(welcomeText, welcomeText)
                    );
                }
            }
            // by calling next() you ensure that the next BotHandler is run.
            await next();
        });
    }
}

module.exports.DentaBot = DentaBot;
`

My index.js

`
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

const path = require('path');

const dotenv = require('dotenv');
// Import required bot configuration.
const ENV_FILE = path.join(__dirname, '.env');
dotenv.config({ path: ENV_FILE });

const restify = require('restify');

// Import required bot services.
// See https://aka.ms/bot-services to learn more about the different parts of a bot.
const { BotFrameworkAdapter } = require('botbuilder');

// This bot's main dialog.
const { DentaBot } = require('./bot');

// Create HTTP server
const server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, () => {
    console.log(`\n${ server.name } listening to ${ server.url }`);
    console.log(
        '\nGet Bot Framework Emulator: https://aka.ms/botframework-emulator'
    );
    console.log('\nTo talk to your bot, open the emulator select "Open Bot"');
});

// Create adapter.
// See https://aka.ms/about-bot-adapter to learn more about how bots work.
const adapter = new BotFrameworkAdapter({
    appId: null, // process.env.MicrosoftAppId,
    appPassword: null // process.env.MicrosoftAppPassword
});

// Catch-all for errors.
const onTurnErrorHandler = async (context, error) => {
    // This check writes out errors to console log .vs. app insights.
    // NOTE: In production environment, you should consider logging this to Azure
    //       application insights.
    console.error(`\n [onTurnError] unhandled error: ${ error }`);

    // Send a trace activity, which will be displayed in Bot Framework Emulator
    await context.sendTraceActivity(
        'OnTurnError Trace',
        `${ error }`,
        'https://www.botframework.com/schemas/error',
        'TurnError'
    );

    // Send a message to the user
    await context.sendActivity('The bot encountered an error or bug.');
    await context.sendActivity(
        'To continue to run this bot, please fix the bot source code.'
    );
};

// Set the onTurnError for the singleton BotFrameworkAdapter.
adapter.onTurnError = onTurnErrorHandler;

// Map configuration values values from .env file into the required format for each service.

const QnAConfiguration = {
    knowledgeBaseId: process.env.QnAKnowledgebaseId,
    endpointKey: process.env.QnAAuthKey,
    host: process.env.QnAEndpointHostName
};

const LuisConfiguration = {
    applicationId: process.env.LuisAppId,
    endpointKey: process.env.LuisAPIKey,
    endpoint: process.env.LuisAPIHostName
};

const SchedulerConfiguration = {
    SchedulerEndpoint: process.env.SchedulerEndpoint
};
// pack each service configuration into
const configuration = {
    QnAConfiguration,
    LuisConfiguration,
    SchedulerConfiguration
};

// Create the main dialog.

const myBot = new DentaBot(configuration, {});

// Listen for incoming requests.
server.post('/api/messages', (req, res) => {
    adapter.processActivity(req, res, async (context) => {
    // Route to main dialog.
        await myBot.run(context);
    });
});

// Listen for Upgrade requests for Streaming.
server.on('upgrade', (req, socket, head) => {
    // Create an adapter scoped to this WebSocket connection to allow storing session data.
    const streamingAdapter = new BotFrameworkAdapter({
        appId: process.env.MicrosoftAppId,
        appPassword: process.env.MicrosoftAppPassword
    });
    // Set onTurnError for the BotFrameworkAdapter created for each connection.
    streamingAdapter.onTurnError = onTurnErrorHandler;

    streamingAdapter.useWebSocket(req, socket, head, async (context) => {
    // After connecting via WebSocket, run this logic for every request sent over
    // the WebSocket connection.
        await myBot.run(context);
    });
});

`

**Comment by Catalyst546** [comment] 2022-06-21 04:46
kindly pardon my formatting
