### ISSUE TITLE
Failed to decrypt conversation id

### ISSUE THREAD

**Issue by anshuman9198** [MicrosoftDocs/bot-docs#1328] opened 2019-08-19 10:17 UTC
I am deploying bot on microsoft teams and  when i am sending bot response for Microsoft teams user  then it gives response 
> "Failed to decrypt conversation id"

----------------------------------------------------------------------------------------------

`https://smba.trafficmanager.net/in/v3/conversations/a:1MvcDR9zbqUyoo0rMVmoKzPEqTwesCZa5RnK8sAB519Ny-3_1TC1f7p5mMEkfPXvwDeVGXks6chC2BA9-pgvn80UI0Pt8DtQb6hUFxuw7zD2ibI7ojELD0KHuM7bmWUjG/activities/1566204912839`

-----------------------------------------------------------------------------------------------

Headers 
Content-Type: application/json
Authorization: somekey

----------------------------------------------------------------------------------------------

BODY
```json
{
   "attachments": [
      {
         "contentType": "image/png",
         "contentUrl": "https://aka.ms/DuckOnARock",
         "name": "duck-on-a-rock.jpg"
      }
   ],
   "replyToId": "1566204912839",
   "recipient": null,
   "from": {
      "name": "ms-dev-1",
      "id": "28:e6615a79-d199-4641-9bb3-22191207af64"
   },
   "text": "Sorry, I did not understand that.",
   "type": "message",
   "conversation": {
      "conversationType": "personal",
      "tenantId": "682c77b5-e369-4e80-94e5-daff9d0843ad",
      "id": "a:1MvcDR9zbqUyoo0rMVmoKzPEqTwesCZa5RnK8sAB519Ny-3_1TC1f7p5mMEkfPXvwDeVGXks6chC2BA9-pgvn80UI0Pt8DtQb6hUFxuw7zD2ibI7ojELD0KHuM7bmWUjG"
   },
   "timestamp": "2017-02-01T21:10:07.437Z"
}
```

-----------------------------------------------------------------------------------------------

RESPONSE

```json
{
    "error": {
        "code": "BadArgument",
        "message": "Failed to decrypt conversation id"
    }
}
```

**Comment by jwiley84** [comment] 2019-08-19 17:27
Hihi! Lots of questions:

Which doc are you following? This doesn't have the standard link. What bot are you trying to deploy? Is it a sample or a bot you created? How are you deploying? Which SDK are you using?

**Comment by anshuman9198** [comment] 2019-08-19 17:52
this microsoft documentation i am following https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-3.0 .

I created  bot and it is working with skype but when it comes to microsoft teams it is not able to return the response to the user because above mentioned  http request is failing. 
I am having java 1.8-SDK

**Comment by anshuman9198** [comment] 2019-08-19 17:59
Basically i am integrating microsoft teams platform with my chatbot and for response to user above mentioned http request is used. when bot is responding to user with http request it is failing bcz  conversation id is not getting  decoded at your end.

**Comment by v-kydela** [comment] 2019-08-20 20:49
@anshuman9198 - Why is your recipient null?

**Comment by anshuman9198** [comment] 2019-08-21 05:22
`{
"text": "Sorry, I did not understand that.",
   "type": "message"
}`
only this much fields are  mandatory rest is optional (tested in skype case) , i tried filling recipient when i hit the api with postman but the response was same. Filling recipient will not solve the problem i guess??

**Comment by v-kydela** [comment] 2019-08-21 18:26
@anshuman9198 

1. Can you provide your relevant bot code?
2. Are you using a bot channels registration in Azure?
3. How are you getting that conversation ID?

**Comment by anshuman9198** [comment] 2019-08-21 18:43
i registered my bot endpoint on azure and it is successfully sending response of user to my bot in below mention format with all ids. Secret token required for header and for that i am making another call.
FROM MS-TEAMS
`{
"text":"22222222222222",
"textFormat":"plain",
"type":"message",
"timestamp":"2019-08-20T06:53:41.7424308Z",
"localTimestamp":"2019-08-20T12:23:41.7424308+05:30",
"id":"1566284021587",
"channelId":"msteams"
,"serviceUrl":"https://smba.trafficmanager.net/in/",
"from":{
"id":"29:1QKK8ef0ZFqdmalsVokXAX1JDZqGt_3IFsarJPhiw87uB8L3EpMf0dH3Yrbn4fITiOjuZP9axH9auJ8SrN42SCA",
"name":"anshuman mishra","aadObjectId":"3d9be23a-2d38-42ce-af72-14de7317ae5b"},
"conversation":
{
"conversationType":"personal",
"tenantId":"682c77b5-e369-4e80-94e5-daff9d0843ad",
"id":"a:1MvcDR9zbqUyoo0rMVmoKzPEqTwesCZa5RnK8sAB519Ny-3_1TC1f7p5mMEkfPXvwDeVGXks6chC2BA9-pgvn80UI0Pt8DtQb6hUFxuw7zD2ibI7ojELD0KHuM7bmWUjG"
}
,"recipient":{
"id":"28:e6615a79-d199-4641-9bb3-22191207af64",
"name":"ms-dev-1"},
"entities":[{
"locale":"en-GB",
"country":"GB",
"platform":"Mac",
"type":"clientInfo"}],
"channelData":{
"tenant":{"id":"682c77b5-e369-4e80-94e5-daff9d0843ad"}},"locale":"en-GB"}`

**Comment by anshuman9198** [comment] 2019-08-21 18:55
Got Microsoft token 
 [ERROR] TEAMS outbound API error, code: 400 , request : `https://smba.trafficmanager.net/in/v3/conversations/a:1MvcDR9zbqUyoo0rMVmoKzPEqTwesCZa5RnK8sAB519Ny-3_1TC1f7p5mMEkfPXvwDeVGXks6chC2BA9-pgvn80UI0Pt8DtQb6hUFxuw7zD2ibI7ojELD0KHuM7bmWUjG/activities/1566413544640	POST	headers:	Content-Type:application/json	Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCIsImtpZCI6ImllX3FXQ1hoWHh0MXpJRXN1NGM3YWNRVkduNCJ9.eyJhdWQiOiJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZDZkNDk0MjAtZjM5Yi00ZGY3LWExZGMtZDU5YTkzNTg3MWRiLyIsImlhdCI6MTU2NjQxMzI1MSwibmJmIjoxNTY2NDEzMjUxLCJleHAiOjE1NjY0MTcxNTEsImFpbyI6IjQyRmdZTGpqZU9sVnVkbWNsbythQ3VVNkp4NFpBZ0E9IiwiYXBwaWQiOiIzYWEwMmYzNi00MzY3LTQwZGUtYTA4My1iY2U4MzVjZmZlOTciLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kNmQ0OTQyMC1mMzliLTRkZjctYTFkYy1kNTlhOTM1ODcxZGIvIiwidGlkIjoiZDZkNDk0MjAtZjM5Yi00ZGY3LWExZGMtZDU5YTkzNTg3MWRiIiwidXRpIjoieS0zTko1OTNTRW03amU1b2otSHJBQSIsInZlciI6IjEuMCJ9.JTQxGR_-Os8cnu2IdWsIOe-sVs0-gOlUytijKPNslpvnedjIAJnRhhpf91tt4rHIY-YuwQ-HFbglP1QmbtFLeVX2BmwvHlup0t37eAkHXiFhViBdt3TN37GIUTPo3MSyq887KUjlavolWKWYnyY-DLBxEb139Ch1X3qQX3hZDkcXUGZ3qTmAv40wF7kuVQfVZtft6IGLugpjQ0uoDM4rFh13I5PZvDRNXke-QF63kRW8Qw1I0SdNOxOJs4G-XPXthvphgX-sE9nYw1-5Y3zk9T6rQj9uKBPHHjdj8_Y-gHrq0SqhzxwKeqTTWOb9fVh1f952pOtRoXDMhuvCSJpMyQ`

**Comment by v-kydela** [comment] 2019-08-21 18:55
@anshuman9198 - Please [format your code correctly](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) in future comments so that other people don't have to do it for you

**Comment by v-kydela** [comment] 2019-08-21 18:57
@anshuman9198 - Please do not post authorization tokens publicly

**Comment by anshuman9198** [comment] 2019-08-21 18:58
ok

**Comment by v-kydela** [comment] 2019-08-21 18:59
@anshuman9198 - Is there a reason you're using the REST API instead of the Bot Builder SDK?

**Comment by anshuman9198** [comment] 2019-08-21 19:01
Bot architecture is like that

**Comment by v-kydela** [comment] 2019-08-21 19:05
@anshuman9198 - I asked for your relevant bot code and you posted more JSON instead. Please provide your bot code so that I can see how your bot is extracting the conversation ID from incoming activities and incorporating it into outgoing activities and sending those activities with the API.

**Comment by anshuman9198** [comment] 2019-08-21 19:12
I have posted the final format of my api call which i am calling  from postman whatever format works there i can manipulate it in code. 
@v-kydela

**Comment by v-kydela** [comment] 2019-08-21 21:21
@anshuman9198 - I can reproduce your issue only by including the wrong conversation ID in the URL. I notice your service URL includes "in" which I presume is for India. Your problem may be region-specific so I will try to escalate the issue and see if anyone knows of any problems with that service URL.

**Comment by v-kydela** [comment] 2019-08-21 22:23
@anshuman9198 - For testing purposes, please try running a bot that uses the Bot Builder SDK and see if you can communicate with it. You can use a template or a sample of your choice: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples

**Comment by v-kydela** [comment] 2019-08-22 18:46
@anshuman9198 - Are you able to send plain text messages (without the image attachment)?

**Comment by anshuman9198** [comment] 2019-08-24 17:44
@v-kydela i tried without the image attachment and the response was the same.

**Comment by Wajeed-msft** [comment] 2019-08-26 10:50
@anshuman9198 - How are you getting user's unique id which we put in members list?  Could you please try following and share your results?

**Request:**
```
POST Your Service URL/v3/conversations/
Authorization: Bearer Your Access Token
Content-Type: application/json

{
  "bot": {
    "id": "28:Your Bot Id",
    "name": "Test Bot"
  },
  "members": [
    {
      "id": "29: Your User Id which you got from conversationUpdate Event"
    }
  ],
  "channelData": {
    "tenant": {
      "id": "[Your Tenant Id]"
    }
  }
}
```
**Response:** 
```
{
    "id": "a:1vkBYFs6uuO6QlN1z7aM1o1V5SS1PEiLwTib_###################"
}
```
And now try sending plain text message to this conversation Id. Please let us know the result.

**Comment by anshuman9198** [comment] 2019-08-26 14:05
Hey i tried above format and got 
```{
    "error": {
        "code": "BadSyntax",
        "message": "Invalid user identity in provided tenant"
    }
}```
also when i googled it found others facing similar issue
`https://stackoverflow.com/questions/57386748/botframework-invalid-user-identity-in-provided-tenant`

**Comment by anshuman9198** [comment] 2019-08-26 14:06
Hey i tried above format and got 
`{
    "error": {
        "code": "BadSyntax",
        "message": "Invalid user identity in provided tenant"
    }
}`
also when i googled it found others facing similar issue
`https://stackoverflow.com/questions/57386748/botframework-invalid-user-identity-in-provided-tenant`

**Comment by anshuman9198** [comment] 2019-08-26 14:08
Hey i tried above format and got 
```
{
    "error": {
        "code": "BadSyntax",
        "message": "Invalid user identity in provided tenant"
    }
}

**Comment by anshuman9198** [comment] 2019-08-26 14:08
also when i googled it found others facing similar issue
`https://stackoverflow.com/questions/57386748/botframework-invalid-user-identity-in-provided-tenant`

**Comment by Wajeed-msft** [comment] 2019-08-26 14:15
How are you getting user's unique id which we put in members list? User is is unique per user per Bot. In your case there is a possibility that it is incorrect . Could you please try with any other user in your tenant?

**Comment by anshuman9198** [comment] 2019-08-26 14:24
ms-teams sends this much information to bot-endpoint and user's unique id is there 
only for secret token i need to make an extra request 
```{
 "text":"222222222222222222222222",
"textFormat":"plain",
"type":"message",
"timestamp":"2019-08-26T13:55:43.9710731Z",
"localTimestamp":"2019-08-26T19:25:43.9710731+05:30",
"id":"15668277######",
"channelId":"msteams",
"serviceUrl":"https://smba.trafficmanager.net/in/",
"from":{ 
 "id":"29:1QKK8ef0ZFqdmalsVokXAX1JDZqGt_3IFsarJPhiw87uB########################",
    "name":"anshuman mishra",
    "aadObjectId":"3d9be23a-2d38-42ce-####-###########"
},
"conversation":{
    "conversationType":"personal",
    "tenantId":"682c77b5-e369-4e80-####-############",
    "id":"a:1MvcDR9zbqUyoo0rMVmoKzPEqTwesCZa5RnK8sAB519Ny-3_1TC1f7p5mMEkfPXvwDeVGXks6chC2BA9-##################################"
},
"recipient":{
      "id":"28:e6615a79-d199-4641-9bb3-#########","name":"ms-dev-1"
}

**Comment by v-kydela** [comment] 2019-08-29 23:22
@anshuman9198 - Are you still working on this?

**Comment by Wajeed-msft** [comment] 2019-08-30 04:44
@anshuman9198 - Could you please confirm you have only one bot which you are using while trying this out? You may get this error if you use conversationId created for one bot to sending message using another bot.

**Comment by anshuman9198** [comment] 2019-08-31 17:54
@Wajeed-msft  yes i have only one bot registered

**Comment by anshuman9198** [comment] 2019-08-31 17:55
@v-kydela yes i am working on it and will try what u suggested

**Comment by v-kydela** [comment] 2019-09-04 15:54
@anshuman9198 - Have you tried it yet?

**Comment by v-kydela** [comment] 2019-09-04 16:58
@anshuman9198 - We can see in our logs that you're using a conversation ID created by a different bot. Your two bots are `3aa02f36-4367-40de-a083-bce835cffe97` & `e6615a79-d199-4641-9bb3-22191207af64`. Can you verify this?

**Comment by anshuman9198** [comment] 2019-09-04 17:27
**e97 is a skype bot and **f64 is ms-teams bot. Unfortunately i lost database so i need to register fresh bot.Also bot registration takes time in Microsoft-teams case.

**Comment by anshuman9198** [comment] 2019-09-04 17:29
I will try with new bot and get back to you.

**Comment by v-kydela** [comment] 2019-09-09 23:56
@anshuman9198 - Do you still need help?

**Comment by anshuman9198** [comment] 2019-09-10 05:47
@v-kydela thank you for the assistance also one closing question on this thread 
audio and video card is supported on teams ?? it is displaying `This card's content could not be displayed` for both the case

**Comment by v-kydela** [comment] 2019-09-10 20:10
@anshuman9198 - You can see in [this thread](https://github.com/Microsoft/BotBuilder-V3/issues/40) that [Teams does not support audio or video cards](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#cards-not-supported-in-teams). You can also see in that thread that it's recommended to use task modules instead. I'm closing this issue now.

**Closed by v-kydela** 2019-09-10 20:10 UTC
Labels: Support, source: customer, type: question

**Comment by weskroesbergen** [comment] 2020-04-03 16:47
@v-kydela I am getting this error when using virtual assistant & bot skills. SSO / tokens pass along fine to skills when using the Emulator, but fails using Teams. It looks like the post to GetSigninResource from the parent / calling bot is passing in the conversation ID of the skill bot, and I'm not quite sure how to override it. I get the signin/verify back to the parent / calling bot, but then it fails out with a 403 posting back to the conversation.

**Comment by bubbis-poncho** [comment] 2020-11-09 21:04
@weskroesbergen  did you ever solve your issue?
Facing the same issue with VA

**Comment by weskroesbergen** [comment] 2020-11-13 14:44
@bubbis-poncho @v-kydela I never got it resolved. :( Hoping 4.11 might have some fixes for me there, but haven't gotten through other backlog items yet.

**Comment by elviraquesadamajorel** [comment] 2023-09-18 12:16
Hello! I know it's been a while since this issue was opened but I'm facing the same problem. I'm trying to send a response back to the user from my bot with the REST API, sending a POST to my ServiceURL but still getting this message:

```
 {'error': {'code': 'BadArgument',
  'message': 'Failed to decrypt conversation id'}}
```

Could you please help me? 

I have a bot deployed in Bot Service, also an Application registered in Azure and the app created in Microsoft Teams.

**Comment by BhavyaDhingra** [comment] 2023-09-27 08:44
@elviraquesadamajorel we are also using the same tech stack and facing the same issue. Did you get any help on this?

**Comment by anudeepak-packirisamy** [comment] 2023-09-27 09:32
We are also facing similar issue, did we get any solution?

**Comment by sueess** [comment] 2023-09-27 09:46
Same here, we just opened another issue with more details. Because we are not sure if it is related to this problem. Please support and share your details too: https://github.com/MicrosoftDocs/msteams-docs/issues/9561

**Comment by sueess** [comment] 2023-09-27 10:18
My conversation did not work at all anymore (MS Teams on Mac). Now, I sent a message on my mobile and afterwards it worked also again on the Desktop.

**Comment by itstaby** [comment] 2023-09-27 10:23
We have also suddenly started seeing this issue for some of our activity. We are using `botbuilder.TurnContext` provided to our callback to send this message and not providing a conversation ID manually. It's also a sporadic issue, not hitting for all cases.

**Comment by mia-le-pandatron** [comment] 2023-09-27 10:41
We also experience this issue. Things suddenly stopped working at around 8:30AM Finnish time. Hoping to find the solution to this issue!

> We have also suddenly started seeing this issue for some of our activity. We are using `botbuilder.TurnContext` provided to our callback to send this message and not providing a conversation ID manually. It's also a sporadic issue, not hitting for all cases.
> 
> We are on nodejs.

**Comment by laxman1983** [comment] 2023-09-27 14:08
Hello All.

We also faced same issue today mornig. To overcome this issue, we scaled out the SKUs by upgrading to the Azure Bot Service Premium Channels , which resolved the unhandled errors and restored bot normal
![team](https://github.com/MicrosoftDocs/bot-docs/assets/18114594/20a85c31-5cd2-47d7-b709-37db1c7bf99b)

.

**Comment by v-kydela** [comment] 2023-09-28 03:53
I suspect the recent wave of problems has nothing to do with the issue that was opened 4 years ago. There may be an outage somewhere, or a breaking change could've been introduced. You're sure to get more attention with a new issue
