### ISSUE TITLE
[Bug Bash] Instructions for creating MSA AppId and AppPassword differs across two pages.

### ISSUE THREAD

**Issue by stevengum** [MicrosoftDocs/bot-docs#1064] opened 2019-04-29 21:23 UTC
**Describe the bug**
"[Tutorials > 1. Create and deploy a basic bot](https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&branch=pr-en-us-1325&tabs=javascript#prerequisites)" indicates that MSA accounts need to go to the Application Registration Portal to get an AppId and AppPassword; which means it differs from the instructions in "[How-To > Deploy your bot to Azure](https://review.docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&branch=pr-en-us-1325&tabs=newrg)".

**Expected behavior**
Similar instructions between the two pages on provisioning an Application Registration.

**Comment by ivorb** [comment] 2019-04-30 17:01
Dupe of #1076 will fix them together

**Closed by ivorb** 2019-04-30 17:01 UTC
Labels: P0, bugbash
