### ISSUE TITLE
Deployment options (classic) is not supported option

### ISSUE THREAD

**Issue by sbaidachni** [MicrosoftDocs/bot-docs#784] opened 2019-01-29 23:00 UTC
What is the sense to have a deployment tutorial for unsupported deployment option: "Deployment Options (Classic) is no longer supported and will be removed from the App Service menu. Click here for the new Deployment Center experience." Please, publish something that is up to date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41386916-1ae4-1a69-855a-c48f3804e673
* Version Independent ID: 180ca783-20c2-672c-303c-69cc8b42e71b
* Content: [Configure continuous deployment for Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-build-continuous-deployment?view=azure-bot-service-4.0)
* Content Source: [articles/bot-service-build-continuous-deployment.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-build-continuous-deployment.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment] 2019-02-07 00:06
This is a duplicate of [issue# 820](https://github.com/MicrosoftDocs/bot-docs/issues/820).

**Closed by Kaiqb** 2019-02-07 00:06 UTC
