### ISSUE TITLE
Not sure this example does what it should

### ISSUE THREAD

**Issue by stevejwebb** [MicrosoftDocs/bot-docs#1628] opened 2020-03-27 12:53 UTC
I thought it shows dialog reuse but can't seem to see that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9577ff-cf56-e5de-84c3-bfe10aab5368
* Version Independent ID: b5d62753-f87b-4673-b09b-a5a3fd9360e8
* Content: [Reuse dialogs - Bot Service - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-compositcontrol?view=azure-bot-service-4.0&tabs=csharp&source=docs#feedback)
* Content Source: [articles/v4sdk/bot-builder-compositcontrol.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-compositcontrol.md)
* Service: **bot-service**
* GitHub Login: @v-ducvo
* Microsoft Alias: **kamrani**

**Comment by emgrol** [comment] 2020-03-31 00:06
duplicate of [issue 1483](https://github.com/MicrosoftDocs/bot-docs/issues/1483) 

Hi @stevejwebb, I agree the name isn't clear. The article was renamed to "Manage dialog complexity" in [PR 1930](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1930), the change should go live soon.

**Comment by emgrol** [comment] 2020-04-03 23:51
Closing now that the changes are live.

**Closed by emgrol** 2020-04-03 23:51 UTC
Labels: duplicate, ready, source: customer
