### ISSUE TITLE
Additional Checks? More info needed

### ISSUE THREAD

**Issue by sammydeprez** [MicrosoftDocs/bot-docs#267] opened 2018-09-10 09:51 UTC
In step 3 of the authentication between bot and bot connector you are writing:
"Additional checks are performed to ensure that the token belongs to the bot that sent the request"

What checks are done? Can I find some more information somewhere?
Our customer needs all details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d58bf70a-3263-93a1-5bc2-085431a7aa6b
* Version Independent ID: c5e3de2f-58ad-1c6a-e0f3-93489d013114
* Content: [Authenticate requests - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-3.0)
* Content Source: [articles/rest-api/bot-framework-rest-connector-authentication.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/rest-api/bot-framework-rest-connector-authentication.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by JonathanFingold** [comment] 2018-09-10 16:00
Duplicate of #259.

**Comment by sammydeprez** [comment] 2018-09-11 08:54
@JonathanFingold This is not a duplicate. This is incomplete information. Please open again

**Comment by JonathanFingold** [comment] 2018-09-11 15:39
@sammydeprez , Very sorry; you are correct. I had too many windows open yesterday.

**Comment by JonathanFingold** [comment] 2018-09-11 15:43
@sammydeprez - you can post questions on [stackoverflow](https://stackoverflow.com/questions/tagged/botframework) to get help from support engineers.

**Closed** 2018-09-21 17:53 UTC
Labels: v3 SDK
