### ISSUE TITLE
Example code function "logMessageText" warnings

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/bot-docs#1164] opened 2019-05-27 16:17 UTC
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/bot-docs.de-DE/issues/3
@chrismade commented 2 days ago
Can someone pls have a look on the example code function "logMessageText" on page:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?tabs=javascript&view=azure-bot-service-4.0
when following the instructions:

build an echo bot using botbuilder:
`yo botbuilder -N "botlog02" -D "test options to log conversations" -T echo`

test --&gt; everything is as expected when running locally on bot emulator 4.4.0

next copy and paste "bot.js" from its first appearance at the very top of the page and overwrite the existing "bot.js" - then testing again, you will see this warning (which says it will become an breaking error in the future so I guess this should be fixed):

```
(node:14516) UnhandledPromiseRejectionWarning: TypeError: Cannot perform 'set' on a proxy that has been revoked
    at adapter.sendActivities.then (D:\daten\bots\botlog02\botlog-02\node_modules\botbuilder-core\lib\turnContext.js:176:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:14516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a
catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
When you comment out the call of function "logMessageText" in "this.onMessage" then no warning appears -

This issue appears even before you proceed and start working with CosmosDB or blob storage - and it will not go away with any of these enhancements.

Usually I don't care much on warnings in example code as it is usually a trade off to make code lean to see what matters - and to catch all imaginable scenarios which obviously make the code more complex.

What worries me even more is that I cannot fix it myself - I can comment out all "turnContext.sendActivity" inside the function which makes the warning(s) go away - but I also would like to understand why the warning comes up at all - Good news: The "turnContext.sendActivity" inside the function are not essential - it is rather for a better understanding to info the user what is going on - so if there is not fix for this issue at least make a box into the doc page that users should ignore the warning and remove all "turnContext.sendActivity" before they move towards production

my node version is:
```
node --version
v10.14.0
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7538ed7a-5bb8-abc0-23e7-5b118e2fd47f
* Version Independent ID: f6181862-6527-6698-afcd-4f6d240123da
* Content: [Write directly to storage - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?tabs=javascript&view=azure-bot-service-4.0)
* Content Source: [articles/v4sdk/bot-builder-howto-v4-storage.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/v4sdk/bot-builder-howto-v4-storage.md)
* Service: **bot-service**
* Sub-service: **sdk**
* GitHub Login: @DeniseMak
* Microsoft Alias: **v-demak**

**Comment by DanDev33** [comment] 2019-05-29 17:01
I've labeled this as a v4 enhancement for our dev team to consider. Thanks!

**Comment by zxyanliu** [comment] 2019-08-14 17:09
Hi Cecilia, 
Thanks for your feedback. I am currently looking into this issue and will get back to you soon. 

Best, 

Yan

**Comment by zxyanliu** [comment] 2019-08-16 20:56
Hi @chrismade 
Thanks for your feedback after I checked the old issue you opened [here](https://github.com/MicrosoftDocs/bot-docs.de-DE/issues/). 

I'd like to double check my understanding of the issue you reported here before we could proceed for a solution: 

You followed this [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?tabs=javascript&view=azure-bot-service-4.0)

1. You built an echo bot using botbuilder:
`yo botbuilder -N "botlog02" -D "test options to log conversations" -T echo`
You tested the echo bot and things worked. 

2. Then you copy and paste the "bot.js" file to some other location and you overwrote the existing "bot.js" file (not the one you copied and pasted). You tested the one you overwrote, and you got some error message as regard to "logMessageText". Things didn't work. 

Please let me know if I have understood this part of your question correctly. 

Best, 

Yan

**Comment by zxyanliu** [comment] 2019-08-16 21:04
Hi @chrismade FYI

I also explored a bit on this [article](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?tabs=javascript&view=azure-bot-service-4.0) and tested the bot. I did not come to the point of using Cosmos DB. 

This is what I got so far: 

1. I checked out a JavaScript echo bot from the [samples](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/02.echo-bot) repo. 

2. I overwrote my bot.js file following instructions [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?tabs=javascript&view=azure-bot-service-4.0). I double checked the code before I tested the bot. 

3. I tested the bot in Emulator and got this: 
![image](https://user-images.githubusercontent.com/32497439/63197992-3fa02800-c02e-11e9-9a61-fb33bde44d45.png)

**Comment by chrismade** [comment] 2019-08-18 13:58
@zxyanliu thx for picking this up - I confirm your summary above is correct #1 you create a simple bot using "yo" and then #2 overwrite bot.js with code from the Microsoft example - you can still compile the code and get something useful / working - however, in console window (where you start 'node index.js' ) you will see warnings - which are not easy to fix - example code people use to learn from should not have warnings

**Comment by zxyanliu** [comment] 2019-08-20 00:17
Hi -
Thanks for your reply. May I ask which Microsoft example did you follow when overwrite your bot.js file?

Thanks.

Yan

**Comment by zxyanliu** [comment] 2019-08-20 00:28
Hi @chrismade
I also have some confusion here: 
What did you mean when you said "get something useful / working", could you please specify? 
Did you mean you got your bot running and got some warnings in the console as well? 

Thanks.

Yan

**Comment by chrismade** [comment] 2019-08-20 04:34
Hi @zxyanliu - it was the first or second example code on that page - if I remember correctly it started with using memorystorage and then explained how to replace it then with cosmosDB and blobstorage - with much more complicated code - it was definitely one of the memorystorage examples - and yes, the code ran and showed the expected behaviour but also showed a warning in the console - and especially this one is my concern:

```[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

because it is indicating that the code will no longer run in future - and I'm still unsure where the unhandled promise rejection is - pls also have a look where the issue started originally on the german page where I filed the issue originally already in english language - before it was closed there and copied into the english section.

**Comment by zxyanliu** [comment] 2019-08-20 05:20
Hi @chrismade

Thanks for letting me know the example code on the article page. 

I have also read the issue you filed on the German page and I totally understand the concern you have when you see such an error. 

I will do my best to run through the process again tomorrow to see if I will see similar warnings and get back to you with any updates. 

Best,

Yan

**Comment by zxyanliu** [comment] 2019-08-20 17:40
Hi @chrismade 

I followed what you did: 
1. [Create a JS bot using Yeoman](https://docs.microsoft.com/en-us/azure/bot-service/javascript/bot-builder-javascript-quickstart?view=azure-bot-service-4.0) 
The echo bot runs and tested with success. 
2. I overwrote the bot.js file followed [this tutorial](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?tabs=javascript&view=azure-bot-service-4.0)
Yes, I got the same type of warning. 
![image](https://user-images.githubusercontent.com/32497439/63370233-9bbcc200-c336-11e9-843e-56272d44bd9d.png)

We need further support to see if this warning will have any effect that @chrismade have mentioned.

Thanks. 

Yan

**Comment by Zerryth** [comment] 2019-08-20 23:03
@zxyanliu @chrismade 

Your errors are happening because you're failing to await on your `turnContext.sendActivity()` calls in your `logMessageText` method.

Simply editing lines 41, 43, 47, 56, 58, 63 to be `await turnContext.sendActivity(...)` makes the warnings go away :)

___
![image](https://user-images.githubusercontent.com/35248895/63390468-18b26080-c364-11e9-81dc-671c8264df8b.png)


Happy Console
![image](https://user-images.githubusercontent.com/35248895/63390459-10f2bc00-c364-11e9-9034-803f0c5250e4.png)

**Comment by zxyanliu** [comment] 2019-08-20 23:49
Thanks! @Zerryth 
I tried and it worked! No more warnings! 

@chrismade Please feel free to try what @Zerryth has recommended. This is what I got: 

![image](https://user-images.githubusercontent.com/32497439/63392111-210d9a00-c36a-11e9-833e-722fe0a75575.png)

Tested in Emulator. 
![image](https://user-images.githubusercontent.com/32497439/63392145-48fcfd80-c36a-11e9-8eb9-dd95e9cc41e2.png)

**Comment by chrismade** [comment] 2019-08-21 07:21
thanks, so simple  - then please fix the examples in the docu - then close this case as solved - thank you so much for your support

**Comment by zxyanliu** [comment] 2019-08-21 07:25
Hi - 
@chrismade I have created PR [1164](https://github.com/MicrosoftDocs/bot-docs-pr/pull/1674) to fix the bugs. You will be able to see the updates in a day or two in the article and then I will close the issue. 

Thanks again for your feedback to help us improve our docs. We really appreciate it. 

Vielen Dank! 

Yan

**Comment by zxyanliu** [comment] 2019-08-23 15:55
Hi - @chrismade 
The issue was resolved and content has been updated and live now [Write directly to storage](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-v4-storage?tabs=javascript&view=azure-bot-service-4.0). 

Therefore closing this issue.

Thanks for your feedback, we really appreciate it. 

Yan

**Closed by zxyanliu** 2019-08-23 15:55 UTC
Labels: Support, source: other, type: feature request, v4 SDK
