### ISSUE TITLE
[BugBash] Remove "MSA" from MSA AppId and MSA App Password 

### ISSUE THREAD

**Issue by EricDahlvang** [MicrosoftDocs/bot-docs#1085] opened 2019-04-29 22:02 UTC
**Describe the bug**
This section: https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-bot?view=azure-bot-service-4.0&branch=pr-en-us-1325#debug-a-javascript-bot-using-command-line-and-emulator

States:

> Since this bot is running locally on your computer, you can leave the MSA app ID and MSA app password fileds blank. 

1) should say MicrosoftAppId and MicrosoftAppPassword  (what is an msa appid, msa app password?)

2) fields is misspelled fileds

**Comment by ivorb** [comment] 2019-04-30 17:01
Dupe of issue #1076, will fix them together

**Closed by ivorb** 2019-04-30 17:01 UTC
Labels: P0, bugbash
