### ISSUE TITLE
Deployment template validation issue

### ISSUE THREAD

**Issue by decherd** [MicrosoftDocs/bot-docs#1746] opened 2020-06-24 13:25 UTC
Using the Python echo-bit example out of the box I got it working on the emulator and am trying to deploy it to Azure. I am following the instructions for: "Deploy via ARM template (with new Resource Group)." I entered the information from the previous steps for the appId and appSecret. I made up values for everything else since I don't have a group or service plan. I am getting this error:

InvalidTemplate - Deployment template validation failed: 'The resource 'Microsoft.Web/serverfarms/echo_bot' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.

I had used 'echo_bot' for newAppServicePlanName="echo_bot" newWebAppName="echo_bot" groupName="echo_bot"

The tutorial makes no mention of editing the ARM template in any way so I'm not sure what I need to do here. I assume there isn't an issue with the template. I followed this tutorial: https://docs.microsoft.com/en-us/azure/bot-service/python/bot-builder-python-quickstart?view=azure-bot-service-4.0

I thought it would be helpful to know what it is that I'm missing from the instructions or know if there is an issue with the template.

**Comment by emgrol** [comment] 2020-06-24 23:06
Hi @decherd, I was able to successfully deploy the Python echo bot from the template so I'm not sure what is causing your issue. Adding the support label to get further assistance.

**Comment by decherd** [comment] 2020-06-25 05:30
That's disappointing. I wiped my directory and started again and I'm getting the exact same issue:

InvalidTemplate - Deployment template validation failed: 'The resource 'Microsoft.Web/serverfarms/bots_service_plan' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.

$ az deployment sub create --template-file "./deploymentTemplates/template-with-new-rg.json" --location "eastus" --parameters appId="----------------" appSecret="--------------" botId="echo_bot_A2!h" botSku=F0 newAppServicePlanName="bots_service_plan" newWebAppName="echo_bot" groupName="my_bots" groupLocation="eastus" newAppServicePlanLocation="eastus" --name "echo_bot"
InvalidTemplate - Deployment template validation failed: 'The resource 'Microsoft.Web/serverfarms/bots_service_plan' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.

**Comment by jwiley84** [comment] 2020-06-25 15:53
Those aren't actually the same issue. The first one say your bot is not defined, the second says your service plan is not defined. A couple of questions: are these both brand new, the bot and the app service plan? Or were either one of them already existing? When you say 'wipe your directory', do you mean that you go into Azure and clear out any resources that were successfully created, even though the deployment failed? If you haven't done that, I recommend you do.

**Comment by decherd** [comment] 2020-06-25 18:13
@jwiley84 Thank you for following up with me. What I meant about wiping the directory is that I deleted my project on my local machine and started the echobot tutorial over and the deploy your bot tutorial over. Yes, everything should be new. All I have in Azure is a new free Azure subscription. I looked and I did have an 'echo_bot' resource group that I have since deleted. As things stand right now I have no resource groups, no resources, no app service plans, nothing. It is my understanding that using the 'template-with-new-rg.json' template that it will create all of these plans, groups, and resources on its own. Is that correct? It is also my understanding that the template uses the parameters passed in via the commands given in the tutorial to deploy these resources and that I don't need to modify the template myself. Please let me know what I'm not understanding here. I've read the information on the ARM templates, and have read and re-read this deploy document and I'm not seeing what I'm missing.

**Comment by jwiley84** [comment] 2020-06-25 18:23
Those are all correct assumptions. With python bots, it's imperative that they are deployed to new resource groups because the way the app is containerized on deployment means it will ultimately fail if you try to  deploy to a resource group that's configured for windows-based services. The easiest way around this is to simply deploy to a new RG. Let me try to deploy a new echo-bot using your `az deployment create` and see if I can get the same errors.

**Comment by jwiley84** [comment] 2020-06-25 18:31
So, before I  tried a repro, I wanted to check your naming conventions. I think the issue is the underscores. I went into azure, just to see if I could make a generic app service plan with _ in the name, and got an error on azure. 
![image](https://user-images.githubusercontent.com/17333688/85778360-56e08500-b6d7-11ea-9f14-0146ba610a50.png)


Can you retry your deployment,  but change your naming convention?

**Comment by decherd** [comment] 2020-06-25 18:45
I switched everything to camelcase as seen below and got this:
$ az deployment sub create --template-file "./deploymentTemplates/template-with-new-rg.json" --location "eastus" --parameters appId="----------" appSecret="---------------" botId="GPEchoBot" botSku=F0 newAppServicePlanName="GPBotsServicePlan" newWebAppName="echoBot" groupName="GPBots" groupLocation="eastus" newAppServicePlanLocation="eastus" --name "echo_bot"
InvalidTemplate - Deployment template validation failed: 'The resource 'Microsoft.Web/serverfarms/GPBotsServicePlan' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.

**Comment by jwiley84** [comment] 2020-06-25 18:46
Ok, I was hoping that would work. Let me try a repro.

**Comment by decherd** [comment] 2020-06-28 14:25
@jwiley84 I don't know if you had any success with this issue but I just wanted to check in and see. Again, if anyone can point me in the right direction I would appreciate it.

**Comment by decherd** [comment] 2020-06-29 09:44
I was able to use Azure CLI and create a resource group myself and then followed the instructions on the deploy page for existing RG "Option 2: New App Service Plan." It worked and I zipped and deployed the python code to Azure. The problem now is that the bot isn't working. When I test in web chat it doesn't do anything. I opened the Log Stream and I see this error:
2020-06-29T09:30:09.094264634Z Updated PYTHONPATH to ':/antenv/lib/python3.7/site-packages'
2020-06-29T09:30:11.185808918Z
2020-06-29T09:30:11.185826819Z Error: class uri 'aiohttp.worker.GunicornWebWorker' invalid or not found:
2020-06-29T09:30:11.185838919Z
2020-06-29T09:30:11.185842519Z [Traceback (most recent call last):
2020-06-29T09:30:11.185846119Z   File "/opt/python/3.7.7/lib/python3.7/site-packages/gunicorn/util.py", line 99, in load_class
2020-06-29T09:30:11.185850119Z     mod = importlib.import_module('.'.join(components))
2020-06-29T09:30:11.185853919Z   File "/opt/python/3.7.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
2020-06-29T09:30:11.185857619Z     return _bootstrap._gcd_import(name[level:], package, level)
2020-06-29T09:30:11.185866020Z   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2020-06-29T09:30:11.185870020Z   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2020-06-29T09:30:11.185873520Z   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
2020-06-29T09:30:11.185877120Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-06-29T09:30:11.185880720Z   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2020-06-29T09:30:11.185884320Z   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2020-06-29T09:30:11.185887820Z   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
2020-06-29T09:30:11.185891420Z ModuleNotFoundError: No module named 'aiohttp'
2020-06-29T09:30:11.185894820Z ]
2020-06-29T09:30:11.185898220Z

This is a very simple bot so I'm really not understanding why I'm having so much trouble getting this running on Azure. My intent was to deploy this simple echo bot, see how I can access it within my O365 tenant and then begin developing the bot I actually want to create for my organization.

**Comment by decherd** [comment] 2020-06-29 11:08
I was able to deploy the app by creating a resource group myself with the Azure CLI and then following the instructions for Option 2 to a New App Service Plan. I still don't know why it wasn't working before to a new RG.

**Comment by jwiley84** [comment] 2020-07-16 20:25
https://github.com/microsoft/BotBuilder-Samples/issues/2583

**Comment by jwiley84** [comment] 2020-07-16 20:25
I haven't forgotten you @decherd I'm chasing down the possibility that there's an underlying issue.

**Comment by jwiley84** [comment] 2020-07-23 18:08
@decherd 

There's something going on with the ARM template deploy-to-new-RG. It's being investigated by the team, but right now, the work around is to create an empty resource group on Azure, then run the command to deploy-to-existing-RG.

I'll update this when I get an answer from the team looking into the problem.

**Comment by EvanOman** [comment] 2020-07-27 02:46
Currently experiencing the same issue trying to deploy a Python Bot following the aforementioned tutorial:

```
InvalidTemplate - Deployment template validation failed: 'The resource 'Microsoft.Web/serverfarms/MyServicePlan' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.
```

I used `cookiecutter` to generate the project according to the tutorial instructions:

```
cookiecutter https://github.com/microsoft/botbuilder-python/releases/download/Templates/echo.zip
```

I can send the deployment template if that would be helpful.

**Comment by jwiley84** [comment] 2020-08-05 17:08
Hi @EvanOman @decherd There is a potential fix in the works at the moment, and should hopefully be cut soon. Thank you for your patience in this!

**Comment by divurgentuser** [comment] 2020-08-25 18:00
@jwiley84  Any update?

**Comment by jwiley84** [comment] 2020-10-07 13:58
Thank you for your patience on this. The ARM templates have been updated. Please use an ARM template from a current sample and attempt to redeploy. I'm going to close this issue. If you continue to have the same problem with deploying, please comment and I will reopen.

**Closed by jwiley84** 2020-10-07 13:58 UTC
Labels: platform: Azure: deployment, source: customer, team: support

**Comment by ChrisVanYperenCiphix** [comment] 2021-02-22 21:44
I got the exact same issue as described above. I followed this tutorial: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-deploy-basic-bot?view=azure-bot-service-4.0&tabs=typescript#option-1-existing-app-service-plan. Everything was going fine until I had to "Deploy via ARM template with new Resource Group" though this command:

`az deployment sub create --template-file "<path-to-template-with-new-rg.json" --location <region-location-name> --parameters appId="<app-id-from-previous-step>" appSecret="<password-from-previous-step>" botId="<id or bot-app-service-name>" botSku=F0 newAppServicePlanName="<new-service-plan-name>" newWebAppName="<bot-app-service-name>" groupName="<new-group-name>" groupLocation="<region-location-name>" newAppServicePlanLocation="<region-location-name>" --name "<bot-app-service-name>"`

I changed the values to the following:
`az deployment sub create --template-file "deploymentTemplates/template-with-new-rg.json" --location westeurope --parameters appId="c5581aff-a2aa-4531-aca6-e64e983746a8" appSecret="123456789123456789" botId="basic-bot-tut" botSku=F0 newAppServicePlanName="basic-bot-tut-service-plan" newWebAppName="basic-bot-tut-webAppName" groupName="basic-bot-tut-groupName" groupLocation="westeurope" newAppServicePlanLocation="westeurope" --name "basic-bot-tut-Name"`

This gave me the following output:
`{"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The resource 'Microsoft.Web/serverfarms/basic-bot-tut-service-plan' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":0,"linePosition":0,"path":""}}]}}`
