### ISSUE TITLE
Wrong parameter (--proj-file) in "Publish your bot to Azure" command

### ISSUE THREAD

**Issue by kriscamilleri** [MicrosoftDocs/bot-docs#698] opened 2019-01-09 18:39 UTC
Currently, the command is documented as below.

`az bot publish --name <bot-resource-name> --proj-file "<project-file-name>" --resource-group <resource-group-name> --code-dir <directory-path> --verbose --version v4`

Unfortunately, this does not work. This returns "az: error: unrecognized arguments: --proj-file <ProjectName>"

I believe instead of _--proj-file_ it ought to be _--proj-name_ instead. Further I believe the response provided by the Azure CLI is also incorrect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa1653-6ab2-730b-5479-81a05b9bb18e
* Version Independent ID: a7c8085e-3b7a-711e-308c-7061176c0a5c
* Content: [Deploy your bot using Azure CLI - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by Kaiqb** [comment] 2019-01-09 18:55
Yes, that is correct. A fix has been checked in, and will be released soon. Thx

**Closed by Kaiqb** 2019-01-09 18:55 UTC

**Comment by narulasrinivas** [comment] 2019-02-11 22:29
@kriscamilleri -  Thanks for saving my day. I was about to debug the root cause 👍
